services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    environment:
      # RaspiServer reverse proxy configuration
      TZ: ${TIMEZONE}
      AGH_CONFIG_DISABLE_UPDATE_CHECK: ${AGH_DISABLE_UPDATE_CHECK:-false}
      AGH_CONFIG_BIND_HOST: ${AGH_BIND_HOST:-0.0.0.0}
      AGH_CONFIG_BIND_PORT: ${AGH_BIND_PORT:-3000}
    volumes:
      - ${VOLUMES_DIR}/adguardhome-work:/opt/adguardhome/work
      - ${VOLUMES_DIR}/adguardhome-conf:/opt/adguardhome/conf
    # network_mode: host
    ports:
      - "${ADGUARDHOME_PORT:-84}:80"    # Web interface
      - "${ADGUARDHOME_DNS_PORT:-53}:53/udp"  # DNS principal
      - "${ADGUARDHOME_DNS_PORT:-53}:53/tcp"  # DNS TCP
      - "${ADGUARDHOME_ADMIN_PORT:-3000}:3000" # Admin interface
      # - "${ADGUARDHOME_DNS_ALT_PORT:-5353}:5353/udp"  # DNS alternativo si es necesario
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      # Caddy reverse proxy configuration
      - "caddy=adguardhome.${RASPISERVER_DOMAINS:-cckdev.es,localhost}"
      - "caddy.reverse_proxy={{upstreams 3000}}"
      - "caddy.header=/ X-Forwarded-Proto {scheme}"
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=network-security"
      - "raspiserver.description=DNS filtering and ad blocking solution"