services:

  cloudflared_cckdev:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_cckdev
    restart: always
    command: tunnel --no-autoupdate run --token ${CCKDEV_TOKEN}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
