services:
  cloudflared_cckdev:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_cckdev
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CCKDEV_TOKEN}
    environment:
      - TUNNEL_TOKEN=${CCKDEV_TOKEN}
      - TUNNEL_NAME=${CLOUDFLARE_TUNNEL_NAME:-cckdev}
      - TZ=${TIMEZONE}
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info", "${CCKDEV_TOKEN}"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.05'
          memory: 64M
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=network-tunnel"
      - "raspiserver.description=Cloudflare tunnel for secure remote access"
