services:
  meshnet:
    image: ghcr.io/mattstechinfo/meshnet:latest
    container_name: meshnet
    restart: unless-stopped
    hostname: ${MESHNET_HOSTNAME:-meshnet}    # Make sure hostname is set! Without it, every restart will add a new peer to your Meshnet.
    env_file: ../apps/tunnel/nordvpn.env
    environment:
      - TZ=${TIMEZONE}
      - NORDVPN_TOKEN=${NORDVPN_TOKEN}
      - NORDVPN_MESHNET=${NORDVPN_MESHNET:-true}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    healthcheck:
      test: ["CMD", "nordvpn", "status"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=network-mesh"
      - "raspiserver.description=NordVPN Meshnet for secure peer-to-peer connections"