services:
  nordvpn:
    build: 
      context: ../apps/nordvpn
    container_name: nordvpn
    environment:
      - TZ=${TIMEZONE}
      - NORDVPN_TOKEN=${NORDVPN_TOKEN} # Asegúrate de definir esta variable en tu .env
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    hostname: ${NORDVPN_MESH_NAME}
    privileged: true
    command: mesh
    restart: always
