# https://hub.docker.com/r/linuxserver/code-server
services:
  code:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      # - PASSWORD=
      # - HASHED_PASSWORD=
      # - SUDO_PASSWORD=
      # - SUDO_PASSWORD_HASH=
      # - PROXY_DOMAIN=code.examples.es
    volumes:
      - ./volumes/code-config:/config
      - ./volumes/code-workspace:/config/workspace
    ports:
      - 8448:8443
    restart: unless-stopped
