services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIR}/portainer/data:/data
    ports:
      - ${PORTAINER_PORT:-9000}:9000

  portainer_agent:
    image: portainer/agent
    container_name: portainer_agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
