services:
  raspiserver-admin:
    build:
      context: ../../apps/raspiserver-admin
      dockerfile: Dockerfile
    container_name: raspiserver-admin
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-Europe/Madrid}
      - RASPISERVER_PATH=/raspiserver
    volumes:
      # Mount the entire repository for management
      - ../..:/raspiserver
      # Docker socket for container management (read-only)
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${RASPISERVER_ADMIN_PORT:-5000}:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    labels:
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=management"
      - "raspiserver.description=RaspiServer web-based admin interface"
    networks:
      - default

networks:
  default:
    name: raspiserver-admin
    driver: bridge
