services:
  soulseek:
    image: realies/soulseek
    container_name: soulseek
    restart: unless-stopped
    volumes:
      - ./volumes/soulseek-appdata:/data/.SoulseekQt
      - ./volumes/soulseek-logs:/data/Soulseek_Chat_Logs
      - ${RASPIMEDIA}/Descargas/Musica/download:/data/Soulseek_Downloads
      - ${RASPIMEDIA}/Descargas/Musica/shared:/data/Soulseek_Shared_Folder
    environment:
      - PGID=100
      - PUID=1000
    ports:
      - 6080:6080
      - 61122:61122 # example listening port, check Options -> Login
      - 61123:61123 # example obfuscated port, check Options -> Login