services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only Docker socket access
    ports:
      - ${PORTAINER_PORT:-9000}:9000
      - ${PORTAINER_EDGE_PORT:-8000}:8000 # Edge agent port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=management"
      - "raspiserver.description=Docker container management interface"

  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: unless-stopped
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer_agent
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    ports:
      - ${PORTAINER_AGENT_PORT:-9001}:9001
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9001"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 64M
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=management"
      - "raspiserver.description=Portainer edge agent for remote management"
