# Definition of pipeline stages
stages:
  - test
  - release
  - sync_beta

# Configuration for SAST (Static Application Security Testing)
sast:
  stage: test
  
# Include templates for SAST and secret detection
include:
- template: Security/SAST.gitlab-ci.yml
- template: Jobs/Secret-Detection.gitlab-ci.yml

# Release job for stable and next version branches
release:
  image: node:20  # Docker image to use
  stage: release  # Pipeline stage
  only:
    - stable  # Only runs on 'stable' branch
    - next  # Only runs on 'next' branch
    - next-major  # Only runs on 'next-major' branch
  when: delayed  # Delayed execution
  start_in: 24 hours  # 24-hour delay
  script:
    - cp .releaserc.changelog .releaserc  # Copy release configuration file
    - npm install semantic-release @semantic-release/gitlab @semantic-release/changelog @semantic-release/git  # Install dependencies
    - npx semantic-release  # Run semantic-release

# Pre-release job for alpha and beta branches
pre-release:
  image: node:20  # Docker image to use
  stage: release  # Pipeline stage
  only:
    - alpha  # Only runs on 'alpha' branch
    - beta  # Only runs on 'beta' branch
  when: delayed  # Delayed execution
  start_in: 30 seconds  # 30-second delay
  script:
    - npm install semantic-release @semantic-release/gitlab @semantic-release/changelog @semantic-release/git  # Install dependencies
    - npx semantic-release  # Run semantic-release

# Job to sync beta branch with stable branch
sync_beta:
  stage: sync_beta  # Pipeline stage
  # only:
    # - stable  # Only runs on 'stable' branch
  script:
    - git config --global user.email "$GITLAB_USER_EMAIL"  # Set Git email using GitLab variable
    - git config --global user.name "$GITLAB_USER_NAME"  # Set Git username using GitLab variable
    - git fetch origin beta  # Fetch latest changes from beta branch
    - git checkout beta || git checkout -b beta  # Switch to beta branch or create it if it doesn't exist
    - git merge --no-ff origin/stable  # Merge changes from stable branch into beta branch
    - git push origin beta  # Push changes to beta branch
  needs:
    - release  # Requires the release job to be completed
  rules:
    - if: '$CI_COMMIT_BRANCH == "stable"'  # Only runs if the branch is 'stable'