version: '3.7'

services:

  hello:
    image: hello-world

# # jellyfin
#   jellyfin:
#     image: linuxserver/jellyfin
#     container_name: jellyfin
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - TZ=Europe/Madrid
#       - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
#     restart: always
#     ports:
#       - 8096:8096
#       - 7359:7359/udp #optional
#       - 1900:1900/udp #optional
#       - 8920:8920 #optional
#     volumes:
#       - /media/carcheky/HDCCK/BibliotecaMultimedia:/BibliotecaMultimedia
#       - /media/carcheky/HDCCK/raspiserver/data/jellyfin/config:/config
#       - /media/carcheky/HDCCK/raspiserver/data/jellyfin/movies:/data/movies
#       - /media/carcheky/HDCCK/raspiserver/data/jellyfin/tvshows:/data/tvshows
#       # - /opt/vc/lib:/opt/vc/lib
#     # devices:
#     #   - /dev/vchiq:/dev/vchi
  
  
  
  # # transmission
  # transmission:
  #   image: linuxserver/transmission:latest
  #   container_name: transmission
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #     - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
  #     - USER=username #optional
  #     - PASS=password #optional
  #     - WHITELIST=iplist #optional
  #     - PEERPORT=peerport #optional
  #     - HOST_WHITELIST=dnsname list #optional
  #   volumes:
  #     - /media/carcheky/HDCCK/raspiserver/data/transmission/data:/config
  #     - /media/carcheky/HDCCK/raspiserver/data/transmission/downloads:/downloads
  #     - /media/carcheky/HDCCK/raspiserver/data/transmission/watch/folder:/watch
  #   ports:
  #     - 9091:9091
  #     - 51413:51413
  #     - 51413:51413/udp
  #   restart: always