# RaspiServer - Docker Compose Configuration Template
#
# Instructions:
# 1. Copy this file to docker-compose.yml: cp docker-compose.example.yml docker-compose.yml
# 2. Copy environment file: cp .env.dist .env  
# 3. Edit .env with your settings
# 4. Uncomment the services you want to run below
# 5. Start services: docker-compose up -d
#
# For detailed setup instructions, see: docs/SETUP.md

include:
  # =============================================================================
  # QUICK START - Basic Media Server Stack
  # =============================================================================
  # Uncomment these for a basic working media server
  # - services/multimedia/jellyfin.yml          # Media streaming server
  # - services/multimedia/sonarr.yml            # TV series management
  # - services/multimedia/radarr.yml            # Movie management
  # - services/multimedia/jellyseerr.yml        # Media request interface
  # - services/multimedia/jellystat.yml         # Jellyfin analytics
  # - services/others/qbittorrent.yml           # Torrent client (VPN protected)

  # =============================================================================
  # MULTIMEDIA SERVICES - Media Streaming & Management
  # =============================================================================
  
  # Core Media Services
  # - services/multimedia/jellyfin.yml          # Media streaming server (Plex alternative)
  # - services/multimedia/plex.yml              # Plex media server
  
  # Media Management (*arr stack)
  # - services/multimedia/sonarr.yml            # TV series automation
  # - services/multimedia/radarr.yml            # Movie automation  
  # - services/multimedia/bazarr.yml            # Subtitle management
  # - services/multimedia/prowlarr.yml          # Indexer management
  # - services/multimedia/readarr.yml           # eBook & audiobook management
  # - services/multimedia/lidarr.yml            # Music management
  # - services/multimedia/mylar3.yml            # Comic book management
  
  # Media Requests & Analytics
  # - services/multimedia/jellyseerr.yml        # Media request management
  # - services/multimedia/wizarr.yml            # User invitation system
  # - services/multimedia/jellystat.yml         # Jellyfin analytics
  # - services/multimedia/janitorr.yml          # Media cleanup automation
  
  # Music & Audio
  # - services/multimedia/soulseekqt.yml        # P2P music sharing

  # =============================================================================
  # NETWORK & SECURITY SERVICES
  # =============================================================================
  
  # DNS & Ad Blocking
  # - services/network/pihole.yml               # Network-wide ad blocker
  # - services/network/adguardhome.yml          # Alternative DNS filtering
  
  # VPN & Security
  # - services/network/nordvpn.yml              # VPN protection
  # - services/network/cloudflared.yml          # Cloudflare tunnel
  # - services/network/authelia.yml             # Authentication gateway
  # - services/network/wireward.yml             # Wireguard VPN manager
  
  # Network Tools
  # - services/network/meshnet.yml              # Mesh networking

  # =============================================================================
  # HOME AUTOMATION & MONITORING
  # =============================================================================
  
  # Smart Home
  # - services/automation/homeassistant.yml     # Smart home hub
  # - services/automation/esphome.yml           # ESP device management
  # - services/automation/mqtt.yml              # IoT messaging broker
  
  # System Monitoring
  # - services/automation/netdata.yml           # Real-time system monitoring
  # - services/automation/uptime-kuma.yml       # Service uptime monitoring
  # - services/automation/kener.yml             # Status page generator

  # =============================================================================
  # PRODUCTIVITY & COLLABORATION
  # =============================================================================
  
  # Cloud Storage & Office
  # - services/productivity/nextcloud.yml       # Self-hosted cloud storage
  # - services/productivity/nextcloud-docker-socket-proxy.yml  # Docker API proxy
  
  # Automation & Workflows
  # - services/productivity/n8n.yml             # Workflow automation
  # - services/productivity/activepieces.yml    # Business automation
  
  # Communication
  # - services/productivity/telegram.yml        # Telegram bot integration

  # =============================================================================
  # MANAGEMENT & ADMINISTRATION
  # =============================================================================
  
  # Container Management
  # - services/management/portainer.yml         # Docker GUI management
  # - services/management/dockge.yml            # Docker compose management
  # - services/management/watchtower.yml        # Automatic container updates
  # - services/management/raspiserver-admin.yml # RaspiServer web admin interface
  
  # Dashboard & Monitoring
  # - services/management/homarr.yml            # Unified dashboard

  # =============================================================================
  # ADDITIONAL SERVICES
  # =============================================================================
  
  # Development & Tools
  # - services/others/code.yml                  # VS Code server
  # - services/others/cosmos.yml                # Application manager
  # - services/others/qbittorrent.yml           # Torrent client
  # - services/others/proxy.yml                 # Reverse proxy
  
  # Specialized Applications  
  # - services/others/thingsboard.yml           # IoT platform
  # - services/others/romassistant.yml          # ROM management