version: '3.7'

services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=username #optional
      - PASS=password #optional
      - WHITELIST=iplist #optional
      - PEERPORT=peerport #optional
      - HOST_WHITELIST=dnsname list #optional
    volumes:
      - /media/carcheky/HDCCK/raspiserver/data/transmission/data:/config
      - /media/carcheky/HDCCK/raspiserver/data/transmission/downloads:/downloads
      - /media/carcheky/HDCCK/raspiserver/data/transmission/watch/folder:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    # restart: unless-stopped