services:

  # watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: --cleanup --interval 3600
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      
  # nginx
  swag:
    image: linuxserver/swag:latest
    container_name: swag
    restart: always
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - URL=${DOMAIN}
      - VALIDATION=http
      - EMAIL=${EMAIL}
      - ONLY_SUBDOMAINS=true #optional
      - STAGING=true #optional
      - SUBDOMAINS=r,ha,jellyfin,prowlarr #optional
    volumes:
      - "${RASPICONFIG}/swag/:/config"
    depends_on:
      - watchtower

  # homeassistant
  homeassistant:
    image: "homeassistant/home-assistant:stable"
    container_name: homeassistant
    restart: always
    privileged: true
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - VIRTUAL_HOST=ha.${DOMAIN}
      - VIRTUAL_PORT=8123
      - LETSENCRYPT_HOST=ha.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    volumes:
      - ${RASPICONFIG}/homeassistant/config:/config
      - ${RASPIMEDIA}:/media/RASPIMEDIA
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/dbus:/run/dbus:ro # bluethooth
      # - /dev/serial/by-path:/dev/serial/by-path
      # - /dev/serial/by-id:/dev/serial/by-id
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      - swag

  # jellyfin
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: always
    # privileged: true
    # network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=jellyfin.${DOMAIN}
      - VIRTUAL_HOST=jellyfin.${DOMAIN}
      - VIRTUAL_PORT=8096
      - LETSENCRYPT_HOST=jellyfin.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    volumes:
      - ${RASPIMEDIA}/BibliotecaMultimedia:/BibliotecaMultimedia
      - ${RASPICONFIG}/jellyfin/config:/config
      - ${RASPICONFIG}/jellyfin/movies:/data/movies
      - ${RASPICONFIG}/jellyfin/tvshows:/data/tvshows
      - /etc/localtime:/etc/localtime:ro
      - /opt/vc/lib:/opt/vc/lib
    devices:
      - /dev/vchiq:/dev/vchi
    depends_on:
      - swag
    ports:
      - 8096:8096
    # # transmission
    # transmission:
    #   image: linuxserver/transmission:latest
    #   container_name: transmission
    #   restart: always
    #   # privileged: true
    #   # network_mode: host
    #   environment:
    #     - PUID=${PUID}
    #     - PGID=${PGID}
    #     - TZ=${TIMEZONE}
    #     - USER=${USER} #optional
    #     - PASS=${PASSWORD} #optional
    #     - VIRTUAL_HOST=tr.${DOMAIN}
    #     - VIRTUAL_PORT=9091
    #     - LETSENCRYPT_HOST=tr.${DOMAIN}
    #     - LETSENCRYPT_EMAIL=${EMAIL}
    #   volumes:
    #     - ${RASPICONFIG}/transmission/config:/config
    #     - ${RASPICONFIG}/transmission/incomplete:/downloads/incomplete
    #     - ${RASPIMEDIA}/transmission/:/downloads
    #   depends_on:
    #     - swag
    #   ports:
    #     - 9091:9091

  # room-assistant
  room-assistant:
    image: mkerix/room-assistant
    container_name: room-assistant
    network_mode: host
    restart: always
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ${RASPICONFIG}/room-assistant/config:/room-assistant/config
    # environment:
    #   RA_GLOBAL_INSTANCE_NAME: living-room
    #   NODE_CONFIG: >
    #     {
    #       "global": {
    #         "integrations": ["homeAssistant", "bluetoothClassic"]
    #       }
    #     }
    depends_on:
      - swag
    cap_add:
      - NET_ADMIN

  # mosquitto
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    network_mode: host
    restart: always
    volumes:
      - ${RASPICONFIG}/mosquitto:/mosquitto
    # ports:
    #   - 1883:1883
    #   - 9001:9001
    depends_on:
      - swag

  # prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    # privileged: true
    # network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=prowlarr.${DOMAIN}
      - VIRTUAL_HOST=prowlarr.${DOMAIN}
      - VIRTUAL_PORT=9696
      - LETSENCRYPT_HOST=prowlarr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - FILE__PASSWORD=${PASSWORD}
    volumes:
      - ${RASPICONFIG}/prowlarr/config:/config
    depends_on:
      - swag
    ports:
      - 9696:9696