services:

# jellyfin http://localhost:8096
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: always
    group_add:
      - "105" 
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=${DOMAIN}
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - ${RASPICONFIG}/jellyfin/config:/config
      - ${RASPICONFIG}/jellyfin/intros:/media/intros
      # - ${RASPICONFIG}/jellyfin/plugins:/var/lib/jellyfin/plugins/
      - ${RASPIMEDIA}:/BibliotecaMultimedia:rw
    # ports:
    #   - 8096:8096
    network_mode: host
    devices:
      - /dev/dri:/dev/dri

# wizarr http://localhost:5690
  wizarr:
    image: ghcr.io/wizarrrr/wizarr:latest
    # image: ghcr.io/wizarrrr/wizarr:v2
    container_name: wizarr
    restart: always
    ports:
      - 5690:5690
    volumes:
      - ${RASPICONFIG}/wizarr/database:/data/database
    environment:
      - APP_URL=https://wizarr.${DOMAIN} #URL at which you will access and share 
      - DISABLE_BUILTIN_AUTH=false #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE} #Set your timezone here
    depends_on:
      - jellyfin

# jellyseerr http://localhost:5055
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/jellyseerr/config:/app/config
    ports:
      - 5055:5055

# transmission http://localhost:9091
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - USER=${USER}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - ${RASPICONFIG}/transmission/config:/config
      - ${RASPIMEDIA}:/BibliotecaMultimedia
    ports:
      - 9091:9091

# prowlarr http://localhost:9696
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/prowlarr/config:/config
    ports:
      - 9696:9696

# radarr http://localhost:7878
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/radarr/config:/config
      - ${RASPIMEDIA}:/BibliotecaMultimedia
    ports:
      - 7878:7878
  
# sonarr http://localhost:8989
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/sonarr/config:/config
      - ${RASPIMEDIA}:/BibliotecaMultimedia
    ports:
      - 8989:8989

# bazarr http://localhost:6767
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/bazarr/config:/config
      - ${RASPIMEDIA}:/BibliotecaMultimedia
    ports:
      - 6767:6767

  # recyclarr:
  #   image: ghcr.io/recyclarr/recyclarr
  #   container_name: recyclarr
  #   restart: always
  #   user: 1000:1000
  #   volumes:
  #     - ${RASPICONFIG}/recyclarr/config:/config
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TIMEZONE}


# # lidarr http://localhost:8686
#   lidarr:
#     image: linuxserver/lidarr:latest
#     container_name: lidarr
#     restart: always
#     environment:
#       - PUID=${PUID}
#       - PGID=${PGID}
#       - TZ=${TIMEZONE}
#     volumes:
#       - ${RASPICONFIG}/lidarr/config:/config
#       - ${RASPIMEDIA}:/BibliotecaMultimedia
#     ports:
#       - 8686:8686
    
# # readarr http://localhost:8787
#   readarr:
#     image: linuxserver/readarr:nightly
#     container_name: readarr
#     restart: always
#     environment:
#       - PUID=${PUID}
#       - PGID=${PGID}
#       - TZ=${TIMEZONE}
#     volumes:
#       - ${RASPICONFIG}/readarr/config:/config
#       - ${RASPIMEDIA}:/BibliotecaMultimedia
#     ports:
#       - 8787:8787