version: '3.7'

services:
# portainer
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
      - 9443:9443
    # restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /media/carcheky/HDCCK/raspiserver/data/portainer/data:/data 

# jellyfin
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    # restart: always
    ports:
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
      - 8920:8920 #optional
      - 8096:8096
    volumes:
      - /media/carcheky/HDCCK/BibliotecaMultimedia:/BibliotecaMultimedia
      - /media/carcheky/HDCCK/raspiserver/data/jellyfin/config:/config
      - /media/carcheky/HDCCK/raspiserver/data/jellyfin/movies:/data/movies
      - /media/carcheky/HDCCK/raspiserver/data/jellyfin/tvshows:/data/tvshows
      - /opt/vc/lib:/opt/vc/lib
    devices:
      - /dev/vchiq:/dev/vchi