services:

  swag:
    image: linuxserver/swag:latest
    restart: always
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - URL=${DOMAIN}
      - VALIDATION=http
      - EMAIL=${EMAIL}
      - ONLY_SUBDOMAINS=true
      - STAGING=false
      - SUBDOMAINS=r,ha,jellyfin,prowlarr,sonarr,radarr,lidarr,transmission,jellyseerr
    volumes:
      - "${RASPICONFIG}/swag/:/config"
      - ${RASPICONFIG}/heimdall/config/www:/heimdall
      - ./configs/nginx/_homeassistant.subdomain.conf:/config/nginx/proxy-confs/_homeassistant.subdomain.conf
      - ./configs/nginx/_jellyfin.subdomain.conf:/config/nginx/proxy-confs/_jellyfin.subdomain.conf
      - ./configs/nginx/_jellyseerr.subdomain.conf:/config/nginx/proxy-confs/_jellyseerr.subdomain.conf
      - ./configs/nginx/_lidarr.subdomain.conf:/config/nginx/proxy-confs/_lidarr.subdomain.conf
      - ./configs/nginx/_prowlarr.subdomain.conf:/config/nginx/proxy-confs/_prowlarr.subdomain.conf
      - ./configs/nginx/_radarr.subdomain.conf:/config/nginx/proxy-confs/_radarr.subdomain.conf
      - ./configs/nginx/_sonarr.subdomain.conf:/config/nginx/proxy-confs/_sonarr.subdomain.conf
      - ./configs/nginx/_transmission.subdomain.conf:/config/nginx/proxy-confs/_transmission.subdomain.conf
      - ./configs/nginx/_heimdall.subdomain.conf:/config/nginx/proxy-confs/_heimdall.subdomain.conf

  heimdall:
    # http://localhost:8080 
    image: linuxserver/heimdall:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/heimdall/config:/config
    ports:
      - 8080:80
    depends_on:
      - swag

  homeassistant:
    # http://localhost:8123
    image: "homeassistant/home-assistant:stable"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/homeassistant/config:/config
      - ${RASPIMEDIA}:/media/RASPIMEDIA
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro # bluethooth
    depends_on:
      - swag
    network_mode: host
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

  jellyfin:
    # http://localhost:8096
    image: linuxserver/jellyfin:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=jellyfin.${DOMAIN}
    volumes:
      - ${RASPICONFIG}/jellyfin/config:/config
      - ${RASPIMEDIA}/BibliotecaMultimedia:/BibliotecaMultimedia
    depends_on:
      - swag
    ports:
      - 8096:8096
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12

  transmission:
    # http://localhost:9091
    image: linuxserver/transmission:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - USER=${USER}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - ${RASPICONFIG}/transmission/config:/config
      - ${RASPIMEDIA}/BibliotecaMultimedia:/BibliotecaMultimedia
    depends_on:
      - swag
    ports:
      - 9091:9091

  radarr:
    # http://localhost:7878
    image: linuxserver/radarr:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/radarr/config:/config
      - ${RASPIMEDIA}/BibliotecaMultimedia:/BibliotecaMultimedia
    depends_on:
      - swag
    ports:
      - 7878:7878

  prowlarr:
    # http://localhost:9696
    image: linuxserver/prowlarr:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/prowlarr/config:/config
    depends_on:
      - swag
    ports:
      - 9696:9696

  jellyseerr:
    # http://localhost:5055
    image: fallenbagel/jellyseerr:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - LOG_LEVEL=info
    volumes:
      - ${RASPICONFIG}/jellyseerr/config:/app/config
    depends_on:
      - swag
    ports:
      - 5055:5055
