version: '3.7'
services:

  # homeassistant
  homeassistant:
    image: linuxserver/homeassistant:latest
    # image: "home-assistant/home-assistant:stable"
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /raspi/MOUNTED_raspiconfig/data/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /raspi/MOUNTED_raspimedia/BibliotecaMultimedia:/media
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/dbus:/run/dbus:ro
    ports:
      - 8123:8123 #optional
    # devices:
    restart: unless-stopped
    privileged: true

  # Proxy the Docker sock so that we can pick up stats for HomeAssistant
  dockerproxy:
    image: tecnativa/docker-socket-proxy
    container_name: dockerproxy
    restart: unless-stopped
    network_mode: host
    depends_on: 
      homeassistant:
          condition: service_started
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2375:2375
    environment:
      - BUILD=1
      - COMMIT=1
      - CONFIGS=1
      - CONTAINERS=1
      - DISTRIBUTION=1
      - EXEC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=1
      - PLUGINS=1
      - SERVICES=1
      - SESSSION=1
      - SWARM=1
      - POST=1

  # jellyfin
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    depends_on: 
      homeassistant:
          condition: service_started
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - JELLYFIN_PublishedServerUrl=192.168.1.201 #optional
    restart: unless-stopped
    ports:
      - 8096:8096
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
      - 8920:8920 #optional
    volumes:
      - /raspi/MOUNTED_raspimedia/BibliotecaMultimedia:/BibliotecaMultimedia
      - /raspi/MOUNTED_raspiconfig/data/jellyfin/config:/config
      - /raspi/MOUNTED_raspiconfig/data/jellyfin/movies:/data/movies
      - /raspi/MOUNTED_raspiconfig/data/jellyfin/tvshows:/data/tvshows
      - /etc/localtime:/etc/localtime:ro
      - /opt/vc/lib:/opt/vc/lib
    devices:
      - /dev/vchiq:/dev/vchi

  # transmission
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      # - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=carcheky #optional
      - PASS=locococo #optional
      # - WHITELIST=iplist #optional
      # - PEERPORT=0 #optional
      # - HOST_WHITELIST=dnsname list #optional
    volumes:
      - /raspi/MOUNTED_raspiconfig/data/transmission/data:/config
      - /raspi/MOUNTED_raspiconfig/data/transmission/downloads:/downloads
      - /raspi/MOUNTED_raspiconfig/data/transmission/watch/folder:/watch
      - /var/run/docker.sock:/var/run/docker.sock
      # - /raspi/MOUNTED_raspimedia/BibliotecaMultimedia:/BibliotecaMultimedia
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
      
  # portainer
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
      - 9443:9443
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /raspi/MOUNTED_raspiconfig/data/portainer/data:/data
    command: --admin-password $$2y$$05$$na4eZ7.5khaaFZbPn3MYieq4x7YGOBBBttedAyPvq2xt8/jfi8goC
