services:

  swag:
    image: linuxserver/swag:latest
    restart: always
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - URL=${DOMAIN}
      - VALIDATION=http
      - EMAIL=${EMAIL}
      - ONLY_SUBDOMAINS=true
      - STAGING=false
      - SUBDOMAINS=r,ha,jellyfin,prowlarr,sonarr,radarr,bazarr,transmission,jellyseerr,wizarr
    volumes:
      - "${RASPICONFIG}/swag/:/config"
      - ${RASPICONFIG}/heimdall/config/www:/heimdall
      - ./configs/nginx/_homeassistant.subdomain.conf:/config/nginx/proxy-confs/_homeassistant.subdomain.conf
      - ./configs/nginx/_jellyfin.subdomain.conf:/config/nginx/proxy-confs/_jellyfin.subdomain.conf
      - ./configs/nginx/_jellyseerr.subdomain.conf:/config/nginx/proxy-confs/_jellyseerr.subdomain.conf
      - ./configs/nginx/_bazarr.subdomain.conf:/config/nginx/proxy-confs/_bazarr.subdomain.conf
      - ./configs/nginx/_prowlarr.subdomain.conf:/config/nginx/proxy-confs/_prowlarr.subdomain.conf
      - ./configs/nginx/_radarr.subdomain.conf:/config/nginx/proxy-confs/_radarr.subdomain.conf
      - ./configs/nginx/_sonarr.subdomain.conf:/config/nginx/proxy-confs/_sonarr.subdomain.conf
      - ./configs/nginx/_transmission.subdomain.conf:/config/nginx/proxy-confs/_transmission.subdomain.conf
      - ./configs/nginx/_homarr.subdomain.conf:/config/nginx/proxy-confs/_homarr.subdomain.conf
      - ./configs/nginx/_wizarr.subdomain.conf:/config/nginx/proxy-confs/_wizarr.subdomain.conf

  homarr:
    # http://localhost:7575
    image: ghcr.io/ajnart/homarr:latest
    restart: always
    environment:
      - PASSWORD=${PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/homarr/config:/app/data/configs
      - ${RASPICONFIG}/homarr/icons:/app/public/iconss
    ports:
      - '7575:7575'

  homeassistant:
    # http://localhost:8123
    image: "homeassistant/home-assistant:stable"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/homeassistant/config:/config
      - ${RASPIMEDIA}:/media/RASPIMEDIA
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro # bluethooth
    network_mode: host
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

  jellyfin:
    # http://localhost:8096
    image: linuxserver/jellyfin:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=jellyfin.${DOMAIN}
    volumes:
      - ${RASPICONFIG}/jellyfin/config:/config
      - ${RASPIMEDIA}/BibliotecaMultimedia:/BibliotecaMultimedia
    ports:
      - 8096:8096
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12

  wizarr:
    # http://localhost:5690
    image: ghcr.io/wizarrrr/wizarr:latest
    restart: always
    user: 1000:1000 #Optional but recommended, sets the user uid that Wizarr will run with
    ports:
      - 5690:5690
    volumes:
      - ${RASPICONFIG}/wizarr/database:/data/database
    environment:
      - APP_URL=https://wizarr.${DOMAIN} #URL at which you will access and share 
      - DISABLE_BUILTIN_AUTH=false #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - TZ=Europe/Madrid #Set your timezone here
    depends_on:
      - jellyfin

  jellyseerr:
    # http://localhost:5055
    image: fallenbagel/jellyseerr:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/jellyseerr/config:/app/config
    ports:
      - 5055:5055

  transmission:
    # http://localhost:9091
    image: linuxserver/transmission:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - USER=${USER}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - ${RASPICONFIG}/transmission/config:/config
      - ${RASPIMEDIA}/BibliotecaMultimedia:/BibliotecaMultimedia
    ports:
      - 9091:9091

  prowlarr:
    # http://localhost:9696
    image: linuxserver/prowlarr:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/prowlarr/config:/config
    ports:
      - 9696:9696

  radarr:
    # http://localhost:7878
    image: linuxserver/radarr:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/radarr/config:/config
      - ${RASPIMEDIA}/BibliotecaMultimedia:/BibliotecaMultimedia
    ports:
      - 7878:7878
  
  sonarr:
    # http://localhost:8989
    image: linuxserver/sonarr:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/sonarr/config:/config
      - ${RASPIMEDIA}/BibliotecaMultimedia:/BibliotecaMultimedia
    ports:
      - 8989:8989

  bazarr:
    # http://localhost:6767
    image: linuxserver/bazarr:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/bazarr/config:/config
      - ${RASPIMEDIA}/BibliotecaMultimedia:/BibliotecaMultimedia
    ports:
      - 6767:6767