services:

  # diun
  diun:
    image: crazymax/diun:latest
    container_name: diun
    privileged: true
    command: serve
    network_mode: host
    volumes:
      - "${DATA_FOLDER}/diun/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Madrid"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
    restart: always

  # nginx
  swag:
    image: linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=carcheky.com
      - VALIDATION=http
      - SUBDOMAINS=r,ha,tr,jf,jd,nc #optional
      # - CERTPROVIDER= #optional
      # - DNSPLUGIN=cloudflare #optional
      # - PROPAGATION= #optional
      - EMAIL= carcheky@gmail.com
      - ONLY_SUBDOMAINS=true #optional
      # - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - "${DATA_FOLDER}/swag/data:/config"
    # ports:
    #   - 443:443
    #   - 80:80 #optional
    restart: unless-stopped
    network_mode: host