version: '3.7'

services:

  # jellyfin
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    restart: unless-stopped
    ports:
      - 80:8096
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
      - 8920:8920 #optional
    volumes:
      - /raspi/MOUNTED_HD/BibliotecaMultimedia:/BibliotecaMultimedia
      - /raspi/MOUNTED_HD/raspiserver/data/jellyfin/config:/config
      - /raspi/MOUNTED_HD/raspiserver/data/jellyfin/movies:/data/movies
      - /raspi/MOUNTED_HD/raspiserver/data/jellyfin/tvshows:/data/tvshows
      # - /opt/vc/lib:/opt/vc/lib
      # devices:
      #   - /dev/vchiq:/dev/vchi


  # homeassistant
  homeassistant:
    image: linuxserver/homeassistant:latest
    # image: "home-assistant/home-assistant:stable"
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /raspi/MOUNTED_HD/raspiserver/data/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /raspi/MOUNTED_HD/BibliotecaMultimedia:/BibliotecaMultimedia
    ports:
      - 8123:8123 #optional
    # devices:
    restart: unless-stopped
    privileged: true

  # homeassistant:
    # container_name: homeassistant

  # # webtop
  # webtop:
  #   image: linuxserver/webtop:alpine-kde
  #   container_name: webtop
  #   security_opt:
  #     - seccomp:unconfined #optional
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Madrid
  #     - SUBFOLDER=/web #optional
  #     - KEYBOARD=es-es-qwerty #optional
  #   volumes:
  #     - /raspi/MOUNTED_HD/raspiserver/data/webtop/config:/config
  #     - /var/run/docker.sock:/var/run/docker.sock #optional
  #   ports:
  #     - 80:3000
  #   # devices:
  #   #   - /dev/dri:/dev/dri #optional
  #   shm_size: "1gb" #optional
  #   restart: unless-stopped




      # # transmission
      # transmission:
      #   image: linuxserver/transmission:latest
      #   container_name: transmission
      #   environment:
      #     - PUID=1000
      #     - PGID=1000
      #     - TZ=Europe/London
      #     - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      #     - USER=username #optional
      #     - PASS=password #optional
      #     - WHITELIST=iplist #optional
      #     - PEERPORT=peerport #optional
      #     - HOST_WHITELIST=dnsname list #optional
      #   volumes:
      #     - /raspi/MOUNTED_HD/raspiserver/data/transmission/data:/config
      #     - /raspi/MOUNTED_HD/raspiserver/data/transmission/downloads:/downloads
      #     - /raspi/MOUNTED_HD/raspiserver/data/transmission/watch/folder:/watch
      #   ports:
      #     - 9091:9091
      #     - 51413:51413
      #     - 51413:51413/udp
      #   restart: unless-stopped
      
      
      # # portainer
      # portainer:
      #   image: portainer/portainer-ce
      #   container_name: portainer
      #   ports:
      #     - 9000:9000
      #     - 8000:8000
      #     - 9443:9443
      #   restart: unless-stopped
      #   volumes:
      #     - /var/run/docker.sock:/var/run/docker.sock
      #     - /raspi/MOUNTED_HD/raspiserver/data/portainer/data:/data
      #   command: --admin-password $$2y$$05$$na4eZ7.5khaaFZbPn3MYieq4x7YGOBBBttedAyPvq2xt8/jfi8goC
