services:

  swag:
    image: linuxserver/swag:latest
    container_name: swag
    restart: always
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ${RASPICONFIG}/swag/config:/config
      - ./configs/nginx/:/config/nginx/proxy-confs/
    environment:
      STAGING: false
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
      EXTRA_DOMAINS: ${DOMAINS}
      EMAIL: ${EMAIL}
      URL: ${DOMAIN}
      VALIDATION: dns
      SUBDOMAINS: wildcard
      DNSPLUGIN: cloudflare
      PROPAGATION: 60
      # DOCKER_MODS: linuxserver/mods:swag-auto-reload|linuxserver/mods:swag-dashboard|linuxserver/mods:universal-cloudflared|linuxserver/mods:swag-cloudflare-real-ip
      DOCKER_MODS: linuxserver/mods:swag-auto-reload|linuxserver/mods:universal-cloudflared|linuxserver/mods:swag-cloudflare-real-ip
    extra_hosts:
      - ${DOMAIN}:127.0.0.1
