services:

  # homeassistant
  homeassistant:
    # image: linuxserver/homeassistant:latest
    image: "homeassistant/home-assistant:stable"
    container_name: homeassistant
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - VIRTUAL_HOST=ha.carcheky.com
      - VIRTUAL_PORT=8123
      - LETSENCRYPT_HOST=ha.carcheky.com
      - LETSENCRYPT_EMAIL=mail@ha.carcheky.com
    volumes:
      - ${DATA_FOLDER}/homeassistant/config:/config
      - ${MEDIA_FOLDER}:/media
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/dbus:/run/dbus:ro # bluethooth
      - ${DATA_FOLDER}/nginx/etc/letsencrypt:/etc/letsencrypt
      - ${DATA_FOLDER}/nginx/var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - 8123:8123 #optional
    restart: unless-stopped
    privileged: true
    entrypoint: /config/init-update-proxy.sh
    depends_on:
      - nginx
    # network_mode: "service:nginx"
    networks:
      raspinet:
        ipv4_address: 172.20.0.10

  # jellyfin
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - JELLYFIN_PublishedServerUrl=carcheky.tplinkdns.com
      - VIRTUAL_HOST=jf.carcheky.com
      - VIRTUAL_PORT=8096
      - LETSENCRYPT_HOST=jf.carcheky.com
      - LETSENCRYPT_EMAIL=mail@jf.carcheky.com
    restart: unless-stopped
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - ${MEDIA_FOLDER}:/BibliotecaMultimedia
      - ${DATA_FOLDER}/nginx/etc/letsencrypt:/etc/letsencrypt
      - ${DATA_FOLDER}/nginx/var/lib/letsencrypt:/var/lib/letsencrypt
      - ${DATA_FOLDER}/jellyfin/config:/config
      - ${DATA_FOLDER}/jellyfin/movies:/data/movies
      - ${DATA_FOLDER}/jellyfin/tvshows:/data/tvshows
      - /etc/localtime:/etc/localtime:ro
      - /opt/vc/lib:/opt/vc/lib
    devices:
      - /dev/vchiq:/dev/vchi
    networks:
      raspinet:
        ipv4_address: 172.20.0.11

  # transmission
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/madrid
      - USER=${USER} #optional
      # - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - PASS=${PASSWORD} #optional
      # - WHITELIST=iplist #optional
      # - PEERPORT="peerport" #optional
      # - HOST_WHITELIST=dnsname list #optional
      - VIRTUAL_HOST=tr.carcheky.com
      - VIRTUAL_PORT=9091
      - LETSENCRYPT_HOST=tr.carcheky.com
      - LETSENCRYPT_EMAIL=mail@tr.carcheky.com
    volumes:
      - ${DATA_FOLDER}/transmission/data:/config
      - ${DATA_FOLDER}/transmission/watch/folder:/watch
      - ${MEDIA_FOLDER}/downloads:/downloads
      - ${DATA_FOLDER}/nginx/etc/letsencrypt:/etc/letsencrypt
      - ${DATA_FOLDER}/nginx/var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      raspinet:
        ipv4_address: 172.20.0.12
        

networks:
  raspinet:
    ipam:
      config:
        - subnet: 172.20.0.0/16