services:

  # diun
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "${DATA_FOLDER}/diun/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Paris"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
    restart: always

  # # duckdns
  # duckdns:
  #   image: linuxserver/duckdns:latest
  #   container_name: duckdns
  #   environment:
  #     - TZ=Europe/Madrid
  #     - SUBDOMAINS=carcheky
  #     - TOKEN=${DUCKDNSTOKEN}
  #   restart: always
  #   depends_on:
  #     - diun
     
  # swag
  swag:
    image: linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=carcheky.tplinkdns.com
      - VALIDATION=http
      - EMAIL=carcheky@gmail.com #optional
    volumes:
      - /raspi/MOUNTED_raspiconfig/data/swag/config:/config
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /raspi/MOUNTED_raspiconfig/data/swag/log:/var/log/letsencrypt
      - ${DATA_FOLDER}/homeassistant:/homeassistant/
      - ${DATA_FOLDER}/jellyfin:/jellyfin/
    ports:
      - 443:443
      - 80:80
    restart: always
    entrypoint: /config/init
 