services:

  # watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: --cleanup --interval 3600

  # nginx
  swag:
    image: linuxserver/swag:latest
    container_name: swag
    restart: always
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - URL=${DOMAIN}
      - VALIDATION=http
      - SUBDOMAINS=r,ha,jf,tr,jd,nc,zb #optional
      # - SUBDOMAINS=r,ha,jf,tr,jd,nc,zb #optional
      - EMAIL=${EMAIL}
      - ONLY_SUBDOMAINS=true #optional
      - STAGING=false #optional
    volumes:
      - "${RASPICONFIG}/swag/:/config"
    depends_on:
      - watchtower

  # homeassistant
  homeassistant:
    image: "homeassistant/home-assistant:stable"
    container_name: homeassistant
    restart: always
    privileged: true
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - VIRTUAL_HOST=ha.${DOMAIN}
      - VIRTUAL_PORT=8123
      - LETSENCRYPT_HOST=ha.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    volumes:
      - ${RASPICONFIG}/homeassistant/config:/config
      - ${RASPIMEDIA}:/media/RASPIMEDIA
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/dbus:/run/dbus:ro # bluethooth
      - /dev/serial/by-id:/dev/serial/by-id
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      - swag

  # jellyfin
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: always
    # privileged: true
    # network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=jf.${DOMAIN}
      - VIRTUAL_HOST=jf.${DOMAIN}
      - VIRTUAL_PORT=8096
      - LETSENCRYPT_HOST=jf.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    volumes:
      - ${RASPIMEDIA}/BibliotecaMultimedia:/BibliotecaMultimedia
      - ${RASPICONFIG}/jellyfin/config:/config
      - ${RASPICONFIG}/jellyfin/movies:/data/movies
      - ${RASPICONFIG}/jellyfin/tvshows:/data/tvshows
      - /etc/localtime:/etc/localtime:ro
      - /opt/vc/lib:/opt/vc/lib
    devices:
      - /dev/vchiq:/dev/vchi
    depends_on:
      - swag
    ports:
      - 8096:8096
  
  # transmission
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: always
    # privileged: true
    # network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - USER=${USER} #optional
      - PASS=${PASSWORD} #optional
      - VIRTUAL_HOST=tr.${DOMAIN}
      - VIRTUAL_PORT=9091
      - LETSENCRYPT_HOST=tr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    volumes:
      - ${RASPICONFIG}/transmission/config:/config
      - ${RASPICONFIG}/transmission/incomplete:/downloads/incomplete
      - ${RASPIMEDIA}/transmission/:/downloads
    depends_on:
      - swag
    ports:
      - 9091:9091

  # # telegram-bot-api
  # telegram-bot-api:
  #   image: riftbit/telegram-bot-api
  #   container_name: telegram-bot-api
  #   restart: always
  #   # privileged: true
  #   network_mode: host
  #   environment:
  #     - API_ID="$TELEGRAM_API_ID"
  #     - API_HASH="$TELEGRAM_API_HASH"
  #     - TELEGRAM_STAT=1
  #     - TELEGRAM_LOG_FILE="/var/lib/telegram-bot-api/telegram-bot-api.log"
  #     - TELEGRAM_PROXY="http://localhost"
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TIMEZONE}
  #     - USER=${USER} #optional
  #     - PASS=${PASSWORD} #optional
  #     - VIRTUAL_HOST=r.${DOMAIN}
  #     - VIRTUAL_PORT=9091
  #     - LETSENCRYPT_HOST=tr.${DOMAIN}
  #     - LETSENCRYPT_EMAIL=${EMAIL}
  #   volumes:
  #     - ${RASPICONFIG}/telegram-bot-api/data:/var/lib/telegram-bot-api
  #   ports:
  #     - 8081:8081
  #     - 8082:8082
  #   depends_on:
  #     - swag
  #   # command: "--help"
  #   command: "--api-id $TELEGRAM_API_ID --api-hash $TELEGRAM_API_HASH --log /var/lib/telegram-bot-api/telegram-bot-api.log --proxy http://localhost:80 --http-port 8081 --http-stat-port 8082 --local -v 3"


  # # mariadb
  # nextcloud-database:
  #   image: mariadb:10.5
  #   container_name: nextcloud-database
  #   restart: always
  #   command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
  #   volumes:
  #     - ${RASPICONFIG}/nextcloud/database/:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
  #     - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
  #     - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
  #     - MYSQL_HOST=nextcloud-database
  #   depends_on:
  #     - watchtower
  #
  # # nextcloud
  # nextcloud-server:
  #   image: nextcloud:latest
  #   container_name: nextcloud-server
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TIMEZONE}
  #     - VIRTUAL_HOST=nc.${DOMAIN}
  #     - VIRTUAL_PORT=8056
  #     - LETSENCRYPT_HOST=nc.${DOMAIN}
  #     - LETSENCRYPT_EMAIL=${EMAIL}
  #     - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
  #     - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
  #     - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
  #     - MYSQL_HOST=nextcloud-database
  #     - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
  #     - NEXTCLOUD_ADMIN_PASSWORD=${PASSWORD}
  #     - NEXTCLOUD_TRUSTED_DOMAINS=nc.${DOMAIN} raspiserver.local:8056 192.168.68.201:8056 localhost
  #     - TRUSTED_PROXIES=127.0.0.1 localhost 192.168.68.201 0.0.0.0 ::1
  #     - OVERWRITEHOST:nc.${DOMAIN}
  #     - OVERWRITEPROTOCOL:https
  #     - OVERWRITECLIURL:https://nc.${DOMAIN}
  #   volumes:
  #     - ${RASPICONFIG}/nextcloud/server:/var/www/html/
  #     - /media/:/media/
  #     # - ${RASPIMEDIA}/nextcloud:/var/www/html/data
  #     # - ${RASPIMEDIA}/BibliotecaMultimedia:/media/BibliotecaMultimedia
  #     # - ${RASPIMEDIA}/transmission:/media/transmission
  #     # - ${RASPICONFIG}/nextcloud/config:/var/www/html/config
  #     # - ${RASPICONFIG}/nextcloud/data:/var/www/html/data:rw
  #     # - ${RASPICONFIG}/nextcloud/custom_apps:/var/www/html/custom_apps
  #     # - ${RASPICONFIG}/nextcloud/themes:/var/www/html/themes/
  #   ports:
  #     - 8056:80
  #   restart: always
  #   links:
  #     - swag
  #     - nextcloud-database
  # 
  #
  # # mqtt
  # mqtt:
  #   container_name: mqtt
  #   image: eclipse-mosquitto:2.0
  #   restart: always
  #   # network_mode: host
  #   volumes:
  #     - "${RASPICONFIG}/mosquitto/data:/mosquitto"
  #   # ports:
  #   #   - "1883:1883"
  #   #   - "9001:9001"
  #   command: "mosquitto -c /mosquitto-no-auth.conf"

  # # zigbee2mqtt
  # zigbee2mqtt:
  #   container_name: zigbee2mqtt
  #   image: koenkk/zigbee2mqtt
  #   platform: linux/arm64/v8
  #   restart: always
  #   # privileged: true
  #   # network_mode: host
  #   volumes:
  #     - ${RASPICONFIG}/zigbee2mqtt/data:/app/data
  #     - /run/udev:/run/udev:ro
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TIMEZONE}
  #     - VIRTUAL_HOST=zb.${DOMAIN}
  #     - VIRTUAL_PORT=8080
  #     - LETSENCRYPT_HOST=r.${DOMAIN}
  #     - LETSENCRYPT_EMAIL=${EMAIL}
  #   devices:
  #     - "/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyUSB0"
  #     # - "/dev/ttyUSB0:/dev/ttyUSB0"
  #   ports:
  #     - "8080:8080"


