version: '3.7'

services:

# portainer
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
      - 9443:9443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /raspi/MOUNTED_HD/raspiserver/data/portainer/data:/data 
    command: --admin-password 