services:
  swag:
    image: linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=carcheky.duckdns.org
      - VALIDATION=dns
      # - SUBDOMAINS=www, #optional
      # - CERTPROVIDER= #optional
      - DNSPLUGIN=duckdns #optional
      # - PROPAGATION=30 #optional
      - EMAIL= carcheky@gmail.com #optional
      # - ONLY_SUBDOMAINS=false #optional
      # - EXTRA_DOMAINS= #optional
      # - STAGING=false #optional
    volumes:
      - /raspi/MOUNTED_raspiconfig/data/swag/config:/config
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  # duckdns
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - TZ=Europe/Madrid
      - SUBDOMAINS=carcheky
      - TOKEN=${DUCKDNSTOKEN}
    restart: unless-stopped

  # homeassistant
  homeassistant:
    # image: linuxserver/homeassistant:latest
    image: "homeassistant/home-assistant:stable"
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /raspi/MOUNTED_raspiconfig/data/homeassistant/config:/config
      - /raspi/MOUNTED_raspiconfig/data/swag/config/keys/letsencrypt:/certificados/
      - /raspi/MOUNTED_raspimedia/BibliotecaMultimedia:/media
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/dbus:/run/dbus:ro
    # ports:
    #   - 8123:8123 #optional
    restart: unless-stopped
    privileged: true

  # jellyfin
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - JELLYFIN_PublishedServerUrl=192.168.1.201 #optional
    restart: unless-stopped
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - /raspi/MOUNTED_raspimedia/BibliotecaMultimedia:/BibliotecaMultimedia
      - /raspi/MOUNTED_raspiconfig/data/swag/config/keys/letsencrypt:/certificados/
      - /raspi/MOUNTED_raspiconfig/data/jellyfin/config:/config
      - /raspi/MOUNTED_raspiconfig/data/jellyfin/movies:/data/movies
      - /raspi/MOUNTED_raspiconfig/data/jellyfin/tvshows:/data/tvshows
      - /etc/localtime:/etc/localtime:ro
      - /opt/vc/lib:/opt/vc/lib
    devices:
      - /dev/vchiq:/dev/vchi
