services:

  # diun
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "${RASPICONFIG}/diun/:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Madrid"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
    restart: always
    labels:
      - "diun.enable=true"

  # nginx
  swag:
    image: linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=carcheky.com
      - VALIDATION=http
      - SUBDOMAINS=r,ha,tr,jf,jd,nc #optional
      - EMAIL=carcheky@gmail.com
      - ONLY_SUBDOMAINS=true #optional
      - STAGING=true #optional
    volumes:
      - "${RASPICONFIG}/swag/:/config"
    restart: always
    network_mode: host
    depends_on:
      - diun

  # transmission
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: always
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/madrid
      - USER=${USER} #optional
      - PASS=${PASSWORD} #optional
      - VIRTUAL_HOST=tr.${DOMAIN}
      - VIRTUAL_PORT=9091
      - LETSENCRYPT_HOST=tr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    volumes:
      - ${RASPICONFIG}/transmission/config:/config
      - ${RASPICONFIG}/transmission/incomplete:/downloads/incomplete
      - ${RASPIMEDIA}/transmission/:/downloads
    network_mode: host
    depends_on:
      - swag