services:

  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.mediacheky.es
      - GENERIC_TIMEZONE=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/n8n/data:/home/node/.n8n
