services:

  # only to maintain this file
  diun:
    image: crazymax/diun:latest

  # # mariadb
  # mariadb:
  #   image: mariadb:10.5
  #   container_name: mariadb
  #   restart: always
  #   command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
  #   volumes:
  #     - ${RASPICONFIG}/mariadb/:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
  #     - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
  #     - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
  #     - MYSQL_HOST=${NEXTCLOUD_MYSQL_HOST}
  
  # # nextcloud
  # nextcloud:
  #   image: nextcloud:latest
  #   container_name: nextcloud
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Madrid
  #     - VIRTUAL_HOST=nc.${DOMAIN}
  #     - VIRTUAL_PORT=8056
  #     - LETSENCRYPT_HOST=nc.${DOMAIN}
  #     - LETSENCRYPT_EMAIL=${EMAIL}
  #     - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
  #     - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
  #     - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
  #     - MYSQL_HOST=${NEXTCLOUD_MYSQL_HOST}
  #     - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
  #     - NEXTCLOUD_ADMIN_PASSWORD=${PASSWORD}
  #     - NEXTCLOUD_TRUSTED_DOMAINS=nc.carcheky.com cckpi.local:8056 192.168.68.201:8056
  #     - TRUSTED_PROXIES=127.0.0.1 localhost 192.168.68.201 0.0.0.0 ::1
  #     - OVERWRITEHOST:nc.carcheky.com
  #     - OVERWRITEPROTOCOL:https
  #     - OVERWRITECLIURL:https://nc.carcheky.com
  #   volumes:
  #     - ${RASPICONFIG}/nextcloud/web:/var/www/html/
  #     # - ${RASPICONFIG}/nextcloud/config:/var/www/html/config
  #     # - ${RASPICONFIG}/nextcloud/data:/var/www/html/data:rw
  #     # - ${RASPICONFIG}/nextcloud/custom_apps:/var/www/html/custom_apps
  #     # - ${RASPICONFIG}/nextcloud/themes:/var/www/html/themes/
  #   ports:
  #     - 8056:80
  #   restart: always
  #   links:
  #     - swag
  #     - mariadb


