services:

  # homeassistant
  homeassistant:
    image: "homeassistant/home-assistant:stable"
    container_name: homeassistant
    restart: always
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - VIRTUAL_HOST=ha.${DOMAIN}
      - VIRTUAL_PORT=8123
      - LETSENCRYPT_HOST=ha.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    volumes:
      - ${DATA_FOLDER}/homeassistant/config:/config
      - ${MEDIA_FOLDER}:/media
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/dbus:/run/dbus:ro # bluethooth
      # - /dev/ttyAMA0:/dev/ttyAMA0
    ports:
      - 8123:8123 #optional
    network_mode: host

  # jellyfin
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: always
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - JELLYFIN_PublishedServerUrl=jf.${DOMAIN}
      - VIRTUAL_HOST=jf.${DOMAIN}
      - VIRTUAL_PORT=8096
      - LETSENCRYPT_HOST=jf.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - ${MEDIA_FOLDER}:/BibliotecaMultimedia
      - ${DATA_FOLDER}/jellyfin/config:/config
      - ${DATA_FOLDER}/jellyfin/movies:/data/movies
      - ${DATA_FOLDER}/jellyfin/tvshows:/data/tvshows
      - /etc/localtime:/etc/localtime:ro
      - /opt/vc/lib:/opt/vc/lib
    devices:
      - /dev/vchiq:/dev/vchi
    network_mode: host

  # transmission
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: always
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/madrid
      - USER=${USER} #optional
      # - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - PASS=${PASSWORD} #optional
      # - WHITELIST=iplist #optional
      # - PEERPORT="peerport" #optional
      # - HOST_WHITELIST=dnsname list #optional
      - VIRTUAL_HOST=tr.${DOMAIN}
      - VIRTUAL_PORT=9091
      - LETSENCRYPT_HOST=tr.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    volumes:
      - ${DATA_FOLDER}/transmission/data:/config
      - ${DATA_FOLDER}/transmission/watch/folder:/watch
      - ${MEDIA_FOLDER}/downloads/transmission:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    network_mode: host
