services:

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: --cleanup --interval 3600
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}

  swag:
    image: linuxserver/swag:latest
    container_name: swag
    restart: always
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - URL=${DOMAIN}
      - VALIDATION=http
      - EMAIL=${EMAIL}
      - ONLY_SUBDOMAINS=true
      - STAGING=false
      - SUBDOMAINS=r,ha,jellyfin,prowlarr,sonarr,radarr,lidarr,transmission,jellyseerr
    volumes:
      - "${RASPICONFIG}/swag/:/config"
      - ./configs/swag/index.html:/config/www/index.html
      - ${RASPICONFIG}/heimdall/config/www:/heimdall
      - ./configs/nginx/_homeassistant.subdomain.conf:/config/nginx/proxy-confs/_homeassistant.subdomain.conf
      - ./configs/nginx/_jellyfin.subdomain.conf:/config/nginx/proxy-confs/_jellyfin.subdomain.conf
      - ./configs/nginx/_jellyseerr.subdomain.conf:/config/nginx/proxy-confs/_jellyseerr.subdomain.conf
      - ./configs/nginx/_lidarr.subdomain.conf:/config/nginx/proxy-confs/_lidarr.subdomain.conf
      - ./configs/nginx/_prowlarr.subdomain.conf:/config/nginx/proxy-confs/_prowlarr.subdomain.conf
      - ./configs/nginx/_radarr.subdomain.conf:/config/nginx/proxy-confs/_radarr.subdomain.conf
      - ./configs/nginx/_sonarr.subdomain.conf:/config/nginx/proxy-confs/_sonarr.subdomain.conf
      - ./configs/nginx/_transmission.subdomain.conf:/config/nginx/proxy-confs/_transmission.subdomain.conf
      - ./configs/nginx/_heimdall.subdomain.conf:/config/nginx/proxy-confs/_heimdall.subdomain.conf
    depends_on:
      - watchtower

  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/heimdall/config:/config
    ports:
      - 8080:80
    depends_on:
      - swag

  homeassistant:
    # https://ha.carcheky.com http://192.168.68.202:8123
    image: "homeassistant/home-assistant:stable"
    container_name: homeassistant
    restart: always
    privileged: true
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RASPICONFIG}/homeassistant/config:/config
      - ${RASPIMEDIA}:/media/RASPIMEDIA
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/dbus:/run/dbus:ro # bluethooth
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      - swag

  jellyfin:
    # jellyfin https://jellyfin.carcheky.com http://192.168.68.202:8096
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=jellyfin.${DOMAIN}
    volumes:
      - ${RASPIMEDIA}/BibliotecaMultimedia:/BibliotecaMultimedia
      - ${RASPICONFIG}/jellyfin/config:/config
      - ${RASPICONFIG}/jellyfin/movies:/data/movies
      - ${RASPICONFIG}/jellyfin/tvshows:/data/tvshows
      - /etc/localtime:/etc/localtime:ro
      - /opt/vc/lib:/opt/vc/lib
    devices:
      - /dev/vchiq:/dev/vchi
    depends_on:
      - swag
    network_mode: host
    # ports:
    #   - 8096:8096

  jellyseerr:
    # jellyseerr https://jellyseerr.carcheky.com http://192.168.68.202:5055
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    ports:
      - 5055:5055
    volumes:
      - ${RASPICONFIG}/jellyseerr/config:/app/config
    volumes_from:
      - jellyfin
    restart: always

  prowlarr:
    # prowlarr https://prowlarr.carcheky.com http://192.168.68.202:9696
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - USER=${USER}
      # - FILE__PASSWORD=${PASSWORD}
    volumes:
      - ${RASPICONFIG}/prowlarr/config:/config
    volumes_from:
      - jellyfin
      - transmission
    depends_on:
      - swag
    network_mode: host
    # ports:
    #   - 9696:9696

  radarr:
    # radarr https://radarr.carcheky.com http://192.168.68.202:7878
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - USER=${USER}
      # - FILE__PASSWORD=${PASSWORD}
    volumes:
      - ${RASPICONFIG}/radarr/config:/config
      # - ${RASPICONFIG}/transmission/downloads:/downloads
      # - ${RASPIMEDIA}/BibliotecaMultimedia/Peliculas:/Peliculas
      # - ${RASPIMEDIA}/BibliotecaMultimedia:/downloads/complete/
    volumes_from:
      - jellyfin
      - transmission
    depends_on:
      - swag
    network_mode: host
    # ports:
    #   - 7878:7878

  transmission:
    # transmission https://transmission.carcheky.com http://192.168.68.202:9091
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - USER=${USER}
      - PASS=${PASSWORD}
    volumes:
      - ${RASPICONFIG}/transmission/config:/config
      - ${RASPICONFIG}/transmission/downloads:/downloads
      # - ${RASPICONFIG}/transmission/downloads/incomplete:/downloads/incomplete
      # - ${RASPICONFIG}/transmission/downloads/complete:/downloads/complete
    depends_on:
      - swag
    network_mode: host
    # ports:
    #   - 9091:9091


  # sonarr:
  #   # sonarr https://sonarr.carcheky.com http://192.168.68.202:8989
  #   image: linuxserver/sonarr:latest
  #   container_name: sonarr
  #   restart: always
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TIMEZONE}
  #     # - FILE__PASSWORD=${PASSWORD}
  #     # - LETSENCRYPT_EMAIL=${EMAIL}
  #     # - LETSENCRYPT_HOST=sonarr.${DOMAIN}
  #     # - VIRTUAL_HOST=sonarr.${DOMAIN}
  #     # - VIRTUAL_PORT=8989
  #   volumes:
  #     - ${RASPICONFIG}/sonarr/config:/config
  #     - ${RASPICONFIG}/sonarr/downloads:/downloads
  #     - ${RASPIMEDIA}/BibliotecaMultimedia:/downloads/complete/
  #   volumes_from:
  #     - jellyfin
  #     - transmission
  #   depends_on:
  #     - swag
  #   network_mode: host
  #   # ports:
  #   #   - 8989:8989
  # lidarr:
  #   # lidarr https://lidarr.carcheky.com http://192.168.68.202:8686
  #   image: linuxserver/lidarr:latest
  #   container_name: lidarr
  #   restart: always
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TIMEZONE}
  #     # - FILE__PASSWORD=${PASSWORD}  
  # #     - LETSENCRYPT_EMAIL=${EMAIL}
  # #     - LETSENCRYPT_HOST=lidarr.${DOMAIN}
  # #     - VIRTUAL_HOST=lidarr.${DOMAIN}
  # #     - VIRTUAL_PORT=8686
  #   volumes:
  #     - ${RASPICONFIG}/lidarr/config:/config
  #     - ${RASPICONFIG}/lidarr/music:/music
  #     - ${RASPICONFIG}/lidarr/downloads:/downloads
  #   depends_on:
  #     - swag
  #   network_mode: host
  #   ports:
  #     - 8686:8686

