services:

  emby:
    image: emby/embyserver
    container_name: embyserver
    runtime: nvidia # Expose NVIDIA GPUs
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - ${RASPICONFIG}/plex/config:/config # Configuration directory
      - ${RASPICONFIG}/Series:/mnt/share1 # Media directory
      - ${RASPICONFIG}/Peliculas:/mnt/share2 # Media directory
    ports:
      - 8076:8096 # HTTP port
      - 8970:8920 # HTTPS port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
      # - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    restart: on-failure