services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 21600 --cleanup --remove-volumes --revive-stopped
    environment:
      - TZ=${TIMEZONE}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
