services:
  uptime-kener:
    image: rajnandan1/kener:latest      # Change to 'rajnandan1/kener:alpine' for an even smaller image! 😁🚀
    container_name: uptime-kener
    # env_file: custom.env              # Uncomment this if you are needing to export environment variables from a custom environment file. By default, Docker will import any variables that exist in `.env`
    environment:
      TZ: Etc/UTC
      KENER_SECRET_KEY: $KENER_SECRET_KEY   # Keep private!! - best to define in `.env` file or through Docker Secret
      ORIGIN: $KENER_ORIGIN
      # DATABASE_URL: custom_db_url     # By default, a SQLite database is used - you may override the database url/type here
      # RESEND_API_KEY: 
      # RESEND_SENDER_EMAIL: 

      ### You most likely will NOT need to change anything below this line. Be sure you know what you're doing!! (https://kener.ing/docs/deployment/#docker-environment-variables)

      # PORT: 3000                      # Port that app listens on in the container
      # KENER_BASE_PATH:                # By default, Kener runs at `/`. You may change this to be, e.g. `/status`, etc. Do NOT add a trailing slash!! (more info here: https://kener.ing/docs/deployment/#docker-environment-variables)
      # ORIGIN: http://localhost:3000
      # NODE_ENV: production            # This is already set to "production" by default within the container
    ports:
      - '3002:3000/tcp'
    volumes:
      - ./volumes/kener-data:/app/database              # We suggest using a Docker named volume, which is more performant for databases
      - ./volumes/kener-uploads:/app/uploads
    # read_only: true                   # Uncommenting this fortifies security by marking the container's filesystem as read-only (aka no data can be written to the container's filesystem except for explicitly defined writable volumes and bind mounts, an exception has already been defined for `/database` and `/uploads`)
    restart: unless-stopped
    # depends_on:                       #  <-- Uncomment if you would like to use PostgreSQL or MySQL
    #   - postgres                      #       ...instead of SQLite
    #   - mysql                         #