services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
    environment:
      - TZ=${TIMEZONE}
      - PLEX_CLAIM=${PLEX_CLAIM}
    network_mode: host
    volumes:
      - ${RASPICONFIG}/plex/database:/config
      - ${RASPICONFIG}/plex/transcode:/transcode
      - ${RASPIMEDIA}:/data
