services:
  # INDEXACIÓN Y GESTIÓN DE CONTENIDO
  
  # INDEXADOR TORRENTS
  # prowlarr http://localhost:9696
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./volumes/prowlarr-config:/config
    ports:
      - 9696:9696
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  # BUSCADOR PELICULAS
  # radarr http://localhost:7878
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK=${UMASK}
      - LANG_FLAGS_WAIT_SECONDS=${LANG_FLAGS_WAIT_SECONDS:-30}
    volumes:
      - ./volumes/radarr-config:/config
      - ${RASPIMEDIA}:/BibliotecaMultimedia
      - ./volumes/radarr-custom-services.d:/custom-services.d
      - ./radarr-arr-scripts:/custom-cont-init.d
      - ./flags:/flags:rw
      - ./volumes/jellyfin-config/:/jellyfin-config:rw
    ports:
      - 7878:7878
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  
  # BUSCADOR SERIES
  # sonarr http://localhost:8989
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}    
      - UMASK=${UMASK}
      - LANG_FLAGS_WAIT_SECONDS=${LANG_FLAGS_WAIT_SECONDS:-30}
    volumes:
      - ./volumes/sonarr-config:/config
      - ${RASPIMEDIA}:/BibliotecaMultimedia
      - ./volumes/sonarr-custom-services.d:/custom-services.d
      - ./sonarr-arr-scripts:/custom-cont-init.d:rw
      - ./flags:/flags:rw
      - ./volumes/jellyfin-config/:/jellyfin-config:rw
    ports:
      - 8989:8989
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # SUBTÍTULOS
  # bazarr http://localhost:6767
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./volumes/bazarr-config:/config
      - ${RASPIMEDIA}:/BibliotecaMultimedia
    ports:
      - 6767:6767
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
  qbitorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./volumes/qbittorrent-config:/config:rw
      - ${RASPIMEDIA}:/BibliotecaMultimedia:rw
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
