services:
  # ESTADÍSTICAS

  jellystat-db:
    image: postgres:15.2
    container_name: jellystat-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./volumes/jellystat-db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: "my-secret-jwt-key"
      TZ: mytimezone # timezone (ex: Europe/Paris)
    volumes:
      - ./volumes/jellystat-backup:/app/backend/backup-data
    ports:
      - "3002:3000"
    depends_on:
      - jellystat-db
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M