services:
  # BUSCADOR MÚSICA
  # lidarr http://localhost:8686
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./volumes/lidarr-config:/config
      - ${RASPIMEDIA}:/BibliotecaMultimedia
    ports:
      - 8686:8686
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M