services:
  # https://docs.linuxserver.io/images/docker-mylar3/
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./volumes/mylar3-config:/config
      - ${RASPIMEDIA}:/BibliotecaMultimedia
    ports:
      - 8090:8090
    restart: always