services:
  # SERVIDOR DE MEDIOS
  
  # jellyfin http://localhost:8096
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: always
    ports:
      - 8096:8096 # access port
      # - 8920:8920 # access port
      # - 7359:7359/udp # optional
      # - 1900:1900/udp # optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=${DOMAIN}
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
      - JELLYFIN_FFmpeg__probesize=1G
      - JELLYFIN_FFmpeg__analyzeduration=500M
    volumes:
      - ./volumes/jellyfin-config:/config
      - ${RASPIMEDIA}:/BibliotecaMultimedia:rw
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "105"
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 2G
        limits:
          cpus: '2'
          memory: 5G