services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - ${N8N_PORT:-5678}:5678
    environment:
      - N8N_PROTOCOL=${N8N_PROTOCOL:-https}
      - N8N_HOST=${N8N_HOST:-n8n.mediacheky.es}
      - N8N_PORT=${N8N_PORT:-5678}:5678
      - NODE_ENV=production
      - WEBHOOK_URL=${N8N_PROTOCOL}://${N8N_HOST}:${N8N_PORT:-5678}/
      - GENERIC_TIMEZONE=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/n8n/data:/home/node/.n8n
