services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:nextcloud-memories
    volumes:
      - ${VOLUMES_DIR}/nextcloud-config:/config
      - ${VOLUMES_DIR}/nextcloud-upload-tmp-dir:/nextcloud-upload-tmp-dir
      - ${NEXTCLOUD_PATH_DATA}:/data
    ports:
      - ${NEXTCLOUD_PORT:-8034}:80
      - ${NEXTCLOUD_SSL_PORT:-4434}:443
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "105" 
    depends_on:
      - nextclouddb

  nextclouddb:
    image: mariadb:11.4
    container_name: nextclouddb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
    volumes:
      - ${VOLUMES_DIR}/nextclouddb-mysql:/var/lib/mysql
