services:
# docker run -e NC_HAPROXY_PASSWORD="some_secure_password" \
#   -v /var/run/docker.sock:/var/run/docker.sock \
#   --name nextcloud-appapi-dsp -h nextcloud-appapi-dsp \
#   --restart unless-stopped --privileged -d ghcr.io/nextcloud/nextcloud-appapi-dsp:release

  nextcloud-appapi-dsp:
    image: ghcr.io/nextcloud/nextcloud-appapi-dsp:latest
    container_name: nextcloud-appapi-dsp
    restart: unless-stopped
    privileged: true
    hostname: nextcloud-appapi-dsp
    environment:
      - TZ=${TIMEZONE}
      - NC_HAPROXY_PASSWORD=${NC_HAPROXY_PASSWORD}
      - NC_HAPROXY_PORT=${NC_HAPROXY_PORT:-80}
      - NC_HAPROXY_SSL_PORT=${NC_HAPROXY_SSL_PORT:-443}
      - NC_HAPROXY_HOST=${NC_HAPROXY_HOST:-nextcloud-appapi-dsp}
      - NC_HAPROXY_MODE=${NC_HAPROXY_MODE:-http}
      - NC_HAPROXY_SSL=${NC_HAPROXY_SSL:-false}
      - NC_HAPROXY_ENABLE=${NC_HAPROXY_ENABLE:-true}
      - NC_HAPROXY_LOG_LEVEL=${NC_HAPROXY_LOG_LEVEL:-info}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only Docker socket access
    ports:
      - ${NC_HAPROXY_PORT:-2375}:${NC_HAPROXY_PORT:-80}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${NC_HAPROXY_PORT:-80}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - nextcloud
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=security-proxy"
      - "raspiserver.description=Secure Docker socket proxy for Nextcloud AppAPI"