services:
  nordvpn:
    build: 
      context: ../apps/nordvpn
      dockerfile: Dockerfile
    container_name: nordvpn
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - NORDVPN_TOKEN=${NORDVPN_TOKEN} # Define esta variable en tu .env
      - NORDVPN_PROTOCOL=${NORDVPN_PROTOCOL:-nordlynx}
      - NORDVPN_COUNTRY=${NORDVPN_COUNTRY:-ES}
      - NORDVPN_CATEGORY=${NORDVPN_CATEGORY:-P2P}
      - CONNECT=${NORDVPN_CONNECT:-true}
      - TECHNOLOGY=${NORDVPN_TECHNOLOGY:-NORDLYNX}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    hostname: ${NORDVPN_MESH_NAME:-nordvpn-server}
    privileged: true
    command: ${NORDVPN_COMMAND:-mesh}
    healthcheck:
      test: ["CMD", "curl", "-f", "--max-time", "10", "https://icanhazip.com/", "||", "exit", "1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=network-security"
      - "raspiserver.description=NordVPN client for secure P2P connections"
