services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      DNSMASQ_LISTENING: all
      CORS_HOSTS: pihole.mediacheky.es
      FTLCONF_LOCAL_IPV4: ${SERVER_IP:-192.168.1.100}
      REV_SERVER: true
      REV_SERVER_TARGET: ${ROUTER_IP:-192.168.1.1}
      REV_SERVER_CIDR: ${NETWORK_CIDR:-192.168.1.0/24}
    volumes:
      - '${CONFIG_DIR}/pihole/etc-pihole:/etc/pihole'
      - '${CONFIG_DIR}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Required for DNS resolution and DHCP functionality
    network_mode: host
    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "-p", "53", "google.com"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=network-security"
      - "raspiserver.description=Network-wide ad blocking and DNS filtering"
    # Alternative port configuration if not using host networking:
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "67:67/udp" # Only required if using Pi-hole as DHCP server
    #   - "${PIHOLE_WEB_PORT:-8080}:80/tcp"
