services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${VOLUMES_DIR}/caddy/data:/data
      - ${VOLUMES_DIR}/caddy/config:/config
    environment:
      - CADDY_INGRESS_NETWORKS=${COMPOSE_PROJECT_NAME:-raspiserver}_default
      - CADDY_DOCKER_CADDYFILE_PATH=-
      - CADDY_DOCKER_POLLING_INTERVAL=5s
      - CADDY_DOCKER_LABEL_PREFIX=caddy
      # Variables para configuración automática
      - RASPISERVER_DOMAINS=${RASPISERVER_DOMAINS:-cckdev.es,localhost}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=reverse-proxy"
      - "raspiserver.description=Automatic reverse proxy with zero configuration"
      # Configuración global de Caddy para rutas /servicio
      - "caddy=localhost"
      - "caddy.handle_path=/jellyfin/* {{reverse_proxy jellyfin:8096}}"
      - "caddy.handle_path=/sonarr/* {{reverse_proxy sonarr:8989}}"
      - "caddy.handle_path=/radarr/* {{reverse_proxy radarr:7878}}"
      - "caddy.handle_path=/jellyseerr/* {{reverse_proxy jellyseerr:5055}}"
      - "caddy.handle_path=/bazarr/* {{reverse_proxy bazarr:6767}}"
      - "caddy.handle_path=/prowlarr/* {{reverse_proxy prowlarr:9696}}"
      - "caddy.handle_path=/homarr/* {{reverse_proxy homarr:7575}}"
      - "caddy.handle_path=/qbittorrent/* {{reverse_proxy qbittorrent:8080}}"
