name: Service Validation
description: Validate individual service functionality and compliance
title: "[Service Validation] {SERVICE_NAME} - Validation and Testing"
labels: ["service-validation", "testing", "documentation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Service Validation Checklist
        
        This issue tracks the validation of a specific service in the RaspiServer infrastructure.
        Each service must be individually tested and validated for proper functionality.

  - type: input
    id: service-name
    attributes:
      label: Service Name
      description: Name of the service being validated
      placeholder: "e.g., jellyfin, sonarr, nextcloud"
    validations:
      required: true

  - type: dropdown
    id: service-category
    attributes:
      label: Service Category
      description: Which category does this service belong to?
      options:
        - automation
        - management
        - multimedia
        - network
        - others
        - productivity
    validations:
      required: true

  - type: checkboxes
    id: validation-checklist
    attributes:
      label: Validation Checklist
      description: Complete validation requirements for the service
      options:
        - label: "📋 **Configuration Validation** - YAML file follows SERVICE_STANDARDS.md"
          required: false
        - label: "🐳 **Docker Compose Validation** - Service can be parsed and validated"
          required: false
        - label: "🚀 **Startup Test** - Service starts successfully without errors"
          required: false
        - label: "🏥 **Health Check** - Service responds to health checks (if applicable)"
          required: false
        - label: "🔌 **Port Accessibility** - Service is accessible on defined ports"
          required: false
        - label: "💾 **Volume Mounts** - All required volumes are properly mounted"
          required: false
        - label: "🔐 **Environment Variables** - All required env vars are defined"
          required: false
        - label: "📊 **Resource Limits** - CPU and memory limits are appropriate"
          required: false
        - label: "🏷️ **Labels & Metadata** - Proper labeling for management tools"
          required: false
        - label: "📚 **Documentation** - Service is documented in docs/SERVICES.md"
          required: false
        - label: "🔄 **Dependencies** - Service dependencies are properly configured"
          required: false
        - label: "🛡️ **Security** - Service follows security best practices"
          required: false

  - type: textarea
    id: test-results
    attributes:
      label: Test Results
      description: Detailed results of validation tests
      placeholder: |
        ## Configuration Test
        - [ ] YAML syntax valid
        - [ ] Follows service standards
        
        ## Startup Test
        - [ ] Container starts successfully
        - [ ] No error logs on startup
        
        ## Functionality Test
        - [ ] Service accessible on expected port
        - [ ] Basic functionality working
        
        ## Issues Found
        - List any issues discovered during validation
        
        ## Additional Notes
        - Any additional observations or recommendations

  - type: textarea
    id: logs
    attributes:
      label: Service Logs
      description: Include relevant logs if there are issues
      render: shell

  - type: checkboxes
    id: final-status
    attributes:
      label: Final Validation Status
      options:
        - label: "✅ **PASSED** - Service is fully functional and compliant"
          required: false
        - label: "⚠️ **PARTIAL** - Service works but has minor issues"
          required: false
        - label: "❌ **FAILED** - Service has significant issues that need fixing"
          required: false