services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      # RaspiServer reverse proxy configuration
      - RASPISERVER_ENABLE=true
      - RASPISERVER_SUBDOMAIN=jellyseerr
      - RASPISERVER_PORT=5055
      - RASPISERVER_PROTOCOL=http
      - RASPISERVER_WEBSOCKET=false
      - RASPISERVER_MAX_BODY_SIZE=100M
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ${VOLUMES_DIR}/jellyseerr-config:/app/config
    ports:
      - ${JELLYSEERR_PORT:-5055}:5055
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5055/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - sonarr
      - radarr
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=media-requests"
      - "raspiserver.description=Media request management for Jellyfin"
