services:
  readarr:
    image: linuxserver/readarr:nightly
    container_name: readarr
    restart: unless-stopped
    environment:
      # RaspiServer reverse proxy configuration
      - RASPISERVER_ENABLE=true
      - RASPISERVER_SUBDOMAIN=readarr
      - RASPISERVER_PORT=8787
      - RASPISERVER_PROTOCOL=http
      - RASPISERVER_WEBSOCKET=false
      - RASPISERVER_MAX_BODY_SIZE=100M
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK=${UMASK:-022}
    volumes:
      - ${VOLUMES_DIR}/readarr-config:/config
      - ${MEDIA_DIR}:/media # Books and audiobooks library
      - ${DOWNLOADS_DIR:-./downloads}:/downloads # Download directory
    ports:
      - ${READARR_PORT:-8787}:8787
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8787/api/v1/system/status?apikey=$$(cat /config/config.xml | grep -oP '(?<=<ApiKey>)[^<]+')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - qbittorrent
      - prowlarr
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=ebook-management"
      - "raspiserver.description=Book and audiobook collection manager"
