services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    restart: unless-stopped
    ports:
      - ${DOCKGE_PORT:-5001}:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only Docker socket
      - ${VOLUMES_DIR}/dockge-data:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - ${DOCKGE_STACKS_DIR:-/opt/stacks}:/opt/stacks
    environment:
      # RaspiServer reverse proxy configuration
      - RASPISERVER_ENABLE=true
      - RASPISERVER_SUBDOMAIN=dockge
      - RASPISERVER_PORT=8080
      - RASPISERVER_PROTOCOL=http
      - RASPISERVER_WEBSOCKET=false
      - RASPISERVER_MAX_BODY_SIZE=100M
      - TZ=${TIMEZONE}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=${DOCKGE_STACKS_DIR:-/opt/stacks}
      - DOCKGE_ENABLE_CONSOLE=${DOCKGE_ENABLE_CONSOLE:-true}
      - DOCKGE_LOG_LEVEL=${DOCKGE_LOG_LEVEL:-info}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=container-management"
      - "raspiserver.description=Modern Docker stack manager with GUI"
