services:
  roomassistant:
    image: mkerix/room-assistant:latest
    container_name: romassistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ${VOLUMES_DIR}/romassistant-config:/room-assistant/config
      - /var/run/dbus:/var/run/dbus:ro
    cap_add:
      - NET_ADMIN
    user: "${PUID:-1000}:${PGID:-100}"
    environment:
      - TZ=${TIMEZONE}
      - NODE_ENV=${NODE_ENV:-production}
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6415/api/health"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=presence-detection"
      - "raspiserver.description=Room-level presence detection for home automation"
