services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    privileged: true
    restart: unless-stopped
    environment:
      # RaspiServer reverse proxy configuration
      - RASPISERVER_ENABLE=true
      - RASPISERVER_SUBDOMAIN=homeassistant
      - RASPISERVER_PORT=8123
      - RASPISERVER_PROTOCOL=http
      - RASPISERVER_WEBSOCKET=true
      - RASPISERVER_MAX_BODY_SIZE=100M
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:homeassistant-hacs
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ${VOLUMES_DIR}/ha-config:/config
      - /run/dbus:/run/dbus:ro # bluetooth communication
      - /dev:/dev:ro # device access for hardware integration
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0" # USB device for integrations (Zigbee, Z-Wave)
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/api/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=home-automation"
      - "raspiserver.description=Home automation and IoT management platform"
