- id: '1673455450832'
  alias: 'Roborock: Limpieza programada'
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  - platform: time
    at: '13:00:00'
  - platform: time
    at: '17:00:00'
  - platform: time
    at: '21:00:00'
  condition: []
  action:
  - device_id: f90f267269373f33820eada09da4a0b0
    domain: vacuum
    entity_id: vacuum.roborock_s6_pure
    type: clean
  mode: single
- id: '1673686532506'
  alias: 'Home Assistant: manda mensaje al iniciar'
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - device_id: 57b12107744bb3c305458a2f262baf92
    domain: mobile_app
    type: notify
    message: iniciado
  mode: single
- id: '1673891885919'
  alias: 'PCCK: auto turn off switch wol'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.pcck
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 3
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.pcck
  mode: single
- id: '1677541510684'
  alias: 'Pixel 4archeky: Avisa que te has quedado dormido'
  description: ''
  trigger: []
  condition: []
  action:
  - service: notify.mobile_app_pixel_4archeky
    data:
      message: durmiendo
      data:
        tag: durmiendo
      title: Hora de ir a dormir
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: notify.mobile_app_pixel_4archeky
    data:
      data:
        tag: durmiendo
      message: clear_notification
      title: Hora de ir a dormir
  - service: scene.turn_on
    target:
      entity_id: scene.a_dormir
    metadata: {}
  mode: single
- id: '1677683749014'
  alias: Apagar salón y despacho tras activar la escena dormitorio trankis
  description: ''
  trigger:
  - platform: state
    entity_id:
    - scene.antes_de_dormir
  condition: []
  action:
  - type: turn_on
    device_id: 6ca15effa507a96063d197cd717d68bc
    entity_id: light.centralita_light
    domain: light
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: scene.turn_on
    target:
      entity_id: scene.despacho_apagado
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.salon_apagado
    metadata: {}
  mode: restart
- id: '1678986779495'
  alias: 'Tabcheky: cargado'
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: 736773a6b456df98196c168dd7b7eaa3
    entity_id: sensor.tabcheky_battery_level
    domain: sensor
    above: 80
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.enchufe_zb_2_switch
      - switch.ladron_socket_1
  mode: single
- id: '1678986795419'
  alias: 'Tabcheky: descargado'
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: 736773a6b456df98196c168dd7b7eaa3
    entity_id: sensor.tabcheky_battery_level
    domain: sensor
    below: 20
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.enchufe_zb_2_switch
      - switch.ladron_socket_1
  mode: single
- id: '1678986877807'
  alias: 'Pixel 4archeky: cargado'
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: 57b12107744bb3c305458a2f262baf92
    entity_id: sensor.pixel_4archeky_battery_level
    domain: sensor
    above: 80
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.ladron_socket_2
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  mode: single
- id: '1678986907570'
  alias: 'Pixel 4archeky: descargado'
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: 882e649114b0dd2467188200ebef3ff4
    entity_id: sensor.pixel_4archeky_battery_level
    domain: sensor
    below: 70
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.ladron_socket_2
  mode: single
- id: '1679915483592'
  alias: Apagar luces de día
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: 57b12107744bb3c305458a2f262baf92
    entity_id: sensor.pixel_4archeky_battery_level
    domain: sensor
    above: 70
  condition:
  - condition: and
    conditions:
    - condition: device
      device_id: 57b12107744bb3c305458a2f262baf92
      domain: device_tracker
      entity_id: device_tracker.pixel_4archeky
      type: is_home
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.pcck
        state: 'on'
      - condition: state
        entity_id: binary_sensor.cmartinezv_lpt
        state: 'on'
    - condition: sun
      after: sunrise
      after_offset: 00:30
  action:
  - type: turn_off
    device_id: b3966c17c5c785d6fcbe3d32b741b298
    entity_id: light.yeelight_color_0x458eb33
    domain: light
  mode: single
- id: '1680088087368'
  alias: 'centralita: encender al detectar movimiento'
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: b978a4f0434103ec02ca8aecf7526a92
    entity_id: binary_sensor.motion_sensor_iaszone
    domain: binary_sensor
  condition:
  - type: is_value
    condition: device
    device_id: 6ca15effa507a96063d197cd717d68bc
    entity_id: sensor.centralita_illuminance
    domain: sensor
    below: 800
  action:
  - type: turn_on
    device_id: 6ca15effa507a96063d197cd717d68bc
    entity_id: light.centralita_light
    domain: light
  mode: single
- id: '1680088128727'
  alias: 'centralita: apagar al no detectar movimiento'
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: b978a4f0434103ec02ca8aecf7526a92
    entity_id: binary_sensor.motion_sensor_iaszone
    domain: binary_sensor
  condition: []
  action:
  - type: turn_off
    device_id: 6ca15effa507a96063d197cd717d68bc
    entity_id: light.centralita_light
    domain: light
  mode: single
- id: '1680089318607'
  alias: 'centralita: apagar si la luz está encendida'
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: 6ca15effa507a96063d197cd717d68bc
    entity_id: sensor.centralita_illuminance
    domain: sensor
    above: 800
  condition:
  - condition: device
    type: is_on
    device_id: 6ca15effa507a96063d197cd717d68bc
    entity_id: light.centralita_light
    domain: light
  action:
  - type: turn_off
    device_id: 6ca15effa507a96063d197cd717d68bc
    entity_id: light.centralita_light
    domain: light
  mode: single
- id: '1680502321908'
  alias: 'centralita: encender si la luz se apaga'
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: 6ca15effa507a96063d197cd717d68bc
    entity_id: sensor.centralita_illuminance
    domain: sensor
    below: 800
  condition:
  - type: is_motion
    condition: device
    device_id: b978a4f0434103ec02ca8aecf7526a92
    entity_id: binary_sensor.motion_sensor_iaszone
    domain: binary_sensor
  action:
  - type: turn_on
    device_id: 6ca15effa507a96063d197cd717d68bc
    entity_id: light.centralita_light
    domain: light
  mode: single
