- id: '1673686532506'
  alias: 'Home Assistant Iniciado '
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.dashboard_mushroom
    metadata: {}
  - device_id: 65122e093172c7ed7dbecd2ab881f12b
    domain: mobile_app
    type: notify
    title: Home assistant
    message: 'Iniciado '
  mode: single
- id: '1691147866863'
  alias: 'TabCheky: carga inteligente '
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /30
    enabled: false
  - platform: state
    entity_id:
    - sensor.tabcheky_battery_level
  condition: []
  action:
  - alias: Tabcheky>80
    if:
    - type: is_battery_level
      condition: device
      device_id: e8ab5d9b84962cf8c1ac97992e3aec1a
      entity_id: c19ed15a9e5bde59f00a04872e707bea
      domain: sensor
      above: 80
    then:
    - service: switch.turn_off
      data: {}
      target:
        entity_id:
        - switch.ladron_socket_2
  - alias: Tabcheky<70
    if:
    - type: is_battery_level
      condition: device
      device_id: e8ab5d9b84962cf8c1ac97992e3aec1a
      entity_id: c19ed15a9e5bde59f00a04872e707bea
      domain: sensor
      below: 70
    then:
    - service: switch.turn_on
      data: {}
      target:
        entity_id:
        - switch.ladron_socket_2
  mode: restart
- id: '1698489590281'
  alias: Casa vacía
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - zone.home
    for:
      hours: 0
      minutes: 5
      seconds: 5
    below: 1
  condition: []
  action:
  - device_id: 65122e093172c7ed7dbecd2ab881f12b
    domain: mobile_app
    type: notify
    message: vacía
    title: Casa
  - service: light.turn_off
    data: {}
    target:
      area_id:
      - despacho
      - dormitorio
      - pasillo
      - salon
  - service: remote.turn_off
    data: {}
    target:
      area_id: salon
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.caldera
  - service: light.turn_off
    data: {}
    target:
      area_id:
      - despacho
      - dormitorio
      - pasillo
      - salon
  - service: homeassistant.turn_off
    target:
      area_id:
      - cocina
      - despacho
      - dormitorio
      - salon
    data: {}
  - service: climate.turn_off
    target:
      area_id:
      - cocina
      - dormitorio
    data: {}
  - service: script.notificacion_casa_vacia
    data:
      field_notify_device: 65122e093172c7ed7dbecd2ab881f12b
      field_title: ''
      field_message: Casa vacía
      field_subtitle: ''
      field_attachment_type: none
      field_attachment_camera_entity: ''
      field_timeout:
        hours: 0
        minutes: 15
        seconds: 0
      field_notification_link: ''
  - service: notify.notify
    metadata: {}
    data:
      title: 'Home Assistant '
      message: 'Parece que no hay nadie en la casa: lo apago todo'
  mode: single
- id: '1701362213795'
  alias: termostato daily off
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: climate.turn_off
    data: {}
    target:
      area_id: cocina
  - device_id: 4cdc09571595831740eb92760584bb20
    domain: climate
    entity_id: 6883f7d7ef018d8f46875a7ecf83c38f
    type: set_hvac_mode
    hvac_mode: 'off'
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.caldera
  - service: notify.notify
    metadata: {}
    data:
      message: Apagado diario de la caldera
  mode: queued
  max: 10
- id: '1701364196838'
  alias: termostato auto
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.temperatura_termostato_temperatura
  - platform: state
    entity_id:
    - input_number.temperatura_deseada
  - platform: state
    entity_id:
    - input_boolean.caldera
  - platform: state
    entity_id:
    - sensor.caldera_accion_hvac
  - platform: state
    entity_id:
    - climate.caldera_termostato
  condition:
  - condition: state
    entity_id: climate.caldera_termostato
    state: heat
  action:
  - if:
    - alias: Cuando la temperatura esté por encima de la deseada
      condition: numeric_state
      entity_id: sensor.temperatura_termostato_temperatura
      above: input_number.temperatura_deseada
    then:
    - service: climate.set_temperature
      data:
        temperature: 7
      target:
        entity_id: climate.caldera_termostato
      alias: poner en espera
    else:
    - service: climate.set_temperature
      data:
        temperature: 30
      target:
        entity_id: climate.caldera_termostato
      alias: Calentar
  mode: restart
- id: '1701364758711'
  alias: termostato caldera helper
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.caldera
  condition: []
  action:
  - if:
    - condition: state
      entity_id: input_boolean.caldera
      state: 'on'
    then:
    - device_id: 4cdc09571595831740eb92760584bb20
      domain: climate
      entity_id: 6883f7d7ef018d8f46875a7ecf83c38f
      type: set_hvac_mode
      hvac_mode: heat
    else:
    - device_id: 4cdc09571595831740eb92760584bb20
      domain: climate
      entity_id: 6883f7d7ef018d8f46875a7ecf83c38f
      type: set_hvac_mode
      hvac_mode: 'off'
  mode: single
- id: '1701965983999'
  alias: Luz despacho botón
  description: '

    '
  trigger:
  - type: turned_on
    platform: device
    device_id: cac8eaf37904039a66158f6e5efb4d69
    entity_id: 835711241331f82a1a83e78e67dd19f1
    domain: binary_sensor
  condition: []
  action:
  - if:
    - condition: or
      conditions:
      - condition: state
        state: 'on'
        entity_id: light.despacho
      - condition: state
        state: 'on'
        entity_id: light.yeelight_color_0x458eb33
    then:
    - service: light.turn_off
      data: {}
      target:
        area_id:
        - despacho
    else:
    - service: light.turn_on
      data:
        brightness_step_pct: 100
        kelvin: 6500
      target:
        entity_id: light.despacho
  mode: single
- id: '1701967185337'
  alias: 'Luz pasillo auto '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presencia_pasillo
  - platform: state
    entity_id:
    - light.gateway_light_7811dcfab2fc
    to: 'on'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.presencia_pasillo
      state: 'on'
    then:
    - service: light.turn_on
      target:
        area_id: pasillo
      data:
        kelvin: 6500
        brightness_pct: 100
    else:
    - service: light.turn_off
      target:
        area_id: pasillo
      data: {}
  mode: restart
- id: '1701992925702'
  alias: Luz despacho auto ON
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.movimiento_despacho
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: sun
      before: sunrise
      after: sunset
      before_offset: '1:00:00'
      after_offset: -0:30:00
      enabled: false
    - condition: numeric_state
      entity_id: zone.home
      above: 0
    - condition: state
      entity_id: light.despacho
      state: 'off'
    - condition: state
      entity_id: light.yeelink_color1_ad66_light
      state: 'off'
    - condition: state
      entity_id: binary_sensor.movimiento_despacho
      state: 'on'
  action:
  - service: homeassistant.update_entity
    target:
      entity_id:
      - binary_sensor.movimiento_despacho_2_movimiento
      - binary_sensor.movimiento_despacho_1_movimiento
    data: {}
  - service: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.despacho_trabajo
  mode: restart
- id: '1702059143983'
  alias: Luz despacho auto OFF
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.movimiento_despacho
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  - platform: state
    entity_id:
    - light.despacho
    to: 'on'
    enabled: true
  - platform: state
    entity_id:
    - light.yeelight_color_0x458eb33
    to: 'on'
  condition: []
  action:
  - if:
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.movimiento_despacho
        state: 'off'
    then:
    - service: light.turn_off
      metadata: {}
      data: {}
      target:
        area_id: despacho
  mode: restart
- id: '1705070087247'
  alias: Llegando a casa marco
  description: ''
  trigger:
  - platform: zone
    entity_id: person.marco
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_chekyphone
    data:
      message: Marco está llegando a casa
  mode: single
- id: '1705070113841'
  alias: 'Llegando a casa chespin '
  description: ''
  trigger:
  - platform: zone
    entity_id: person.chespin
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_chekyphone
    data:
      message: Chespin está llegando a casa
  mode: single
- id: '1708559253093'
  alias: luz dormitorio durmiendo
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.cckmazfit_trigger_2
    attribute: last_updated
  condition:
  - condition: device
    device_id: 65122e093172c7ed7dbecd2ab881f12b
    domain: device_tracker
    entity_id: 3cb76db02ad65e9e4e08270b078b7157
    type: is_home
  action:
  - service: notify.mobile_app_tabcheky
    data:
      message: "Parece que te dormiste \U0001F634\U0001F4A4\U0001F4A4"
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id: dormitorio
  - service: media_player.media_pause
    target:
      entity_id: media_player.jellyfin_lenovo_yt_x705f
    data: {}
  mode: single
- id: '1713360723075'
  alias: smart salón
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.movimiento_extra_movimiento
    - binary_sensor.presencia_salon_ocupacion
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - alias: apaga si no hay movimiento
    if:
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.presencia_salon_ocupacion
        state: 'off'
      - condition: state
        entity_id: binary_sensor.movimiento_extra_movimiento
        state: 'off'
    then:
    - service: light.turn_off
      target:
        area_id:
        - salon
        entity_id:
        - light.enchufe_2_interruptor
        - light.salon
      data: {}
  - alias: por la tarde/noche, enciende si hay movimiento
    if:
    - condition: and
      conditions:
      - condition: sun
        before: sunrise
        after: sunset
        enabled: true
        before_offset: '1:00:00'
        after_offset: -0:45:00
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.presencia_salon_ocupacion
          state: 'on'
        - condition: state
          entity_id: binary_sensor.movimiento_extra_movimiento
          state: 'on'
      - condition: numeric_state
        entity_id: zone.home
        above: 0
    then:
    - service: light.turn_on
      metadata: {}
      data: {}
      target:
        area_id: salon
        entity_id:
        - light.salon
  mode: single
- id: '1713363099665'
  alias: Amanecer anochecer
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - service: notify.mobile_app_chekyphone
    metadata: {}
    data:
      message: El sol ha atravesado el horizonte
  mode: single
- id: '1713364815825'
  alias: Luz dormitorio botón
  description: '

    '
  trigger:
  - type: turned_on
    platform: device
    device_id: a7d977c7678c671a77dbc66e88edf3b5
    entity_id: 27576fc5181f3d5141f35984490826c9
    domain: binary_sensor
  condition: []
  action:
  - if:
    - condition: or
      conditions:
      - condition: state
        state: 'on'
        entity_id: light.dormitorio
      - condition: state
        state: 'on'
        entity_id: light.yeelight_color_0x330dc29
    then:
    - service: light.turn_off
      data: {}
      target:
        area_id:
        - dormitorio
    else:
    - service: light.turn_on
      data:
        brightness_step_pct: 100
        kelvin: 6500
      target:
        area_id: dormitorio
  mode: single
- id: '1713365585382'
  alias: Luz despacho bypass
  description: '

    '
  trigger:
  - type: turned_on
    platform: device
    device_id: cac8eaf37904039a66158f6e5efb4d69
    entity_id: 835711241331f82a1a83e78e67dd19f1
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 4
  condition: []
  action:
  - if:
    - condition: or
      conditions:
      - condition: state
        state: 'on'
        entity_id: light.despacho
      - condition: state
        state: 'on'
        entity_id: light.yeelight_color_0x458eb33
    then:
    - service: light.turn_off
      data: {}
      target:
        area_id:
        - despacho
    else:
    - service: scene.turn_on
      metadata: {}
      target:
        entity_id: scene.despacho_trabajo
    enabled: false
  - service: automation.turn_off
    metadata: {}
    data:
      stop_actions: true
    target:
      entity_id:
      - automation.luz_despacho_auto_off
      - automation.luz_despacho_auto
  - service: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.despacho_gamming
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.despacho_trabajo
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.despacho_trabajo
  mode: single
- id: '1713391309080'
  alias: luz apagar si estoy fuera
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 26188fad9e08f8810d6bbb0e6c536128
    entity_id: 059aee9b6060f3f93cff1c350aa90284
    domain: binary_sensor
  - type: not_opened
    platform: device
    device_id: 26188fad9e08f8810d6bbb0e6c536128
    entity_id: 059aee9b6060f3f93cff1c350aa90284
    domain: binary_sensor
  - platform: state
    entity_id:
    - binary_sensor.sensor_puerta_apertura
    - binary_sensor.sensor_puerta_apertura_2
  - platform: state
    entity_id:
    - light.dormitorio
    - light.yeelight_color_0x330dc29
  condition: []
  action:
  - if:
    - condition: state
      entity_id: person.carcheky
      state: not_home
    then:
    - service: light.turn_off
      metadata: {}
      data: {}
      target:
        area_id: dormitorio
  mode: single
- id: '1713479413152'
  alias: Smart dormitorio
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.movimiento_dormitorio_movimiento
  - platform: state
    entity_id:
    - binary_sensor.sensor_puerta_apertura
  condition:
  - condition: state
    entity_id: person.carcheky
    state: home
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.sensor_puerta_apertura
        state: 'on'
      - condition: state
        entity_id: binary_sensor.movimiento_dormitorio_movimiento
        state: 'on'
      sequence:
      - service: light.turn_on
        metadata: {}
        data: {}
        target:
          area_id: dormitorio
      alias: Abierto abierto
    - conditions:
      - condition: state
        entity_id: binary_sensor.sensor_puerta_apertura
        state: 'off'
      - condition: state
        entity_id: binary_sensor.movimiento_dormitorio_movimiento
        state: 'on'
      sequence:
      - service: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: light.yeelight_color_0x330dc29
      - if:
        - condition: time
          after: '23:00:00'
        then:
        - delay:
            hours: 0
            minutes: 2
            seconds: 0
            milliseconds: 0
        - service: light.turn_off
          metadata: {}
          data: {}
          target:
            entity_id:
            - light.dormitorio
      alias: Cerrado abierto
    - conditions:
      - condition: state
        entity_id: binary_sensor.sensor_puerta_apertura
        state: 'on'
      - condition: state
        entity_id: binary_sensor.movimiento_dormitorio_movimiento
        state: 'off'
      sequence:
      - delay:
          hours: 0
          minutes: 5
          seconds: 0
          milliseconds: 0
      - service: light.turn_off
        target:
          entity_id:
          - light.yeelight_color_0x330dc29
        data: {}
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.dormitorio
      alias: Abierto cerrado
    - conditions:
      - condition: state
        entity_id: binary_sensor.sensor_puerta_apertura
        state: 'off'
      - condition: state
        entity_id: binary_sensor.movimiento_dormitorio_movimiento
        state: 'off'
      sequence:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.dormitorio
      - delay:
          hours: 0
          minutes: 5
          seconds: 0
          milliseconds: 0
      - service: light.turn_off
        target:
          entity_id:
          - light.yeelight_color_0x330dc29
        data: {}
      alias: Cerrado cerrado
  mode: restart
