- id: '1673455450832'
  alias: 'Roborock: Limpieza programada'
  description: ''
  trigger:
  - platform: time
    at: '11:00:00'
  - platform: time
    at: sensor.sun_next_noon
  - platform: time
    at: sensor.sun_next_dusk
  condition: []
  action:
  - device_id: f90f267269373f33820eada09da4a0b0
    domain: vacuum
    entity_id: vacuum.roborock_s6_pure
    type: clean
  mode: single
- id: '1673686532506'
  alias: 'Home Assistant: manda mensaje al iniciar'
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - device_id: 1434f347839ffff0fa9439a0f56dae34
    domain: mobile_app
    type: notify
    message: Iniciado
  mode: single
- id: '1673891885919'
  alias: 'PCCK: auto turn off switch wol'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.pcck
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 3
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.pcck
  mode: single
- id: '1677541510684'
  alias: 'Pixel 4archeky: Avisa que te has quedado dormido'
  description: ''
  trigger: []
  condition: []
  action:
  - service: notify.mobile_app_pixel_4archeky
    data:
      message: durmiendo
      data:
        tag: durmiendo
      title: Hora de ir a dormir
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: notify.mobile_app_pixel_4archeky
    data:
      data:
        tag: durmiendo
      message: clear_notification
      title: Hora de ir a dormir
  - service: scene.turn_on
    target:
      entity_id: scene.a_dormir
    metadata: {}
  mode: single
- id: '1677683749014'
  alias: Apagar salón y despacho tras activar la escena dormitorio trankis
  description: ''
  trigger:
  - platform: state
    entity_id:
    - scene.antes_de_dormir
  condition: []
  action:
  - type: turn_on
    device_id: 1a9b9c8cac9ce05a5fc7b8d7fb367511
    entity_id: light.gateway_light_7811dcfab2fc
    domain: light
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: scene.turn_on
    target:
      entity_id: scene.despacho_apagado
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.salon_apagado
    metadata: {}
  mode: restart
- id: '1678986779495'
  alias: Carga inteligente!!!!
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /10
  condition: []
  action:
  - if:
    - type: is_battery_level
      condition: device
      device_id: 1434f347839ffff0fa9439a0f56dae34
      entity_id: sensor.chekyphone_battery_level
      domain: sensor
      above: 80
    then:
    - service: switch.turn_off
      data: {}
      target:
        entity_id: switch.ladron_socket_2
    alias: ChekyPhone>80
  - if:
    - type: is_battery_level
      condition: device
      device_id: 1434f347839ffff0fa9439a0f56dae34
      entity_id: sensor.chekyphone_battery_level
      domain: sensor
      below: 75
    then:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.ladron_socket_2
    alias: ChekyPhone<75
  - if:
    - type: is_battery_level
      condition: device
      device_id: 736773a6b456df98196c168dd7b7eaa3
      entity_id: sensor.tabcheky_battery_level
      domain: sensor
      above: 80
    then:
    - service: switch.turn_off
      data: {}
      target:
        entity_id: switch.tabcheky_switch
    alias: Tabcheky>80
  - if:
    - type: is_battery_level
      condition: device
      device_id: 736773a6b456df98196c168dd7b7eaa3
      entity_id: sensor.tabcheky_battery_level
      domain: sensor
      below: 70
    then:
    - service: switch.turn_on
      data: {}
      target:
        entity_id:
        - switch.tabcheky_switch
    alias: Tabcheky<70
  mode: single
- id: '1679915483592'
  alias: Apagar luces de día
  description: ''
  trigger: []
  condition:
  - condition: and
    conditions:
    - condition: device
      device_id: 1434f347839ffff0fa9439a0f56dae34
      domain: device_tracker
      entity_id: device_tracker.chekyphone
      type: is_home
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.pcck
        state: 'on'
      - condition: state
        entity_id: binary_sensor.cmartinezv_lpt
        state: 'on'
    - condition: sun
      after: sunrise
      after_offset: 00:30
  action:
  - type: turn_off
    device_id: b3966c17c5c785d6fcbe3d32b741b298
    entity_id: light.yeelight_color_0x458eb33
    domain: light
  mode: single
- id: '1680088087368'
  alias: 'centralita: encender al detectar movimiento'
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: b978a4f0434103ec02ca8aecf7526a92
    entity_id: binary_sensor.motion_sensor_iaszone
    domain: binary_sensor
  condition:
  - condition: device
    type: is_off
    device_id: 1a9b9c8cac9ce05a5fc7b8d7fb367511
    entity_id: light.gateway_light_7811dcfab2fc
    domain: light
  action:
  - type: turn_on
    device_id: 1a9b9c8cac9ce05a5fc7b8d7fb367511
    entity_id: light.gateway_light_7811dcfab2fc
    domain: light
  mode: single
- id: '1680088128727'
  alias: 'centralita: apagar al no detectar movimiento'
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: b978a4f0434103ec02ca8aecf7526a92
    entity_id: binary_sensor.motion_sensor_iaszone
    domain: binary_sensor
  condition: []
  action:
  - type: turn_off
    device_id: 1a9b9c8cac9ce05a5fc7b8d7fb367511
    entity_id: light.gateway_light_7811dcfab2fc
    domain: light
  mode: single
- id: '1680089318607'
  alias: 'centralita: apagar si la luz está encendida'
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: 6ca15effa507a96063d197cd717d68bc
    entity_id: sensor.centralita_illuminance
    domain: sensor
    above: 800
  condition:
  - condition: device
    type: is_on
    device_id: 1a9b9c8cac9ce05a5fc7b8d7fb367511
    entity_id: light.gateway_light_7811dcfab2fc
    domain: light
  action:
  - type: turn_off
    device_id: 1a9b9c8cac9ce05a5fc7b8d7fb367511
    entity_id: light.gateway_light_7811dcfab2fc
    domain: light
  mode: single
- id: '1680502321908'
  alias: 'centralita: encender si la luz se apaga'
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: 6ca15effa507a96063d197cd717d68bc
    entity_id: sensor.centralita_illuminance
    domain: sensor
    below: 800
  condition:
  - type: is_motion
    condition: device
    device_id: b978a4f0434103ec02ca8aecf7526a92
    entity_id: binary_sensor.motion_sensor_iaszone
    domain: binary_sensor
  action:
  - type: turn_off
    device_id: 1a9b9c8cac9ce05a5fc7b8d7fb367511
    entity_id: light.gateway_light_7811dcfab2fc
    domain: light
  mode: single
- id: '1681256957217'
  alias: 'Botón trankis '
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: a7d977c7678c671a77dbc66e88edf3b5
    entity_id: binary_sensor.boton_mesita
    domain: binary_sensor
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.antes_de_dormir
    metadata: {}
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.gateway_light_7811dcfab2fc
  mode: single
- id: '1683544113914'
  alias: 'freidora: notificación al apagar'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.xiaomi_airfryer_freidora
    from: 'on'
    to: 'off'
  condition: []
  action:
  - if:
    - condition: device
      device_id: 57b12107744bb3c305458a2f262baf92
      domain: device_tracker
      entity_id: device_tracker.pixel_4archeky
      type: is_home
    then:
    - service: notify.mobile_app_pixel_4archeky
      data:
        message: la freidora ha terminado
        target: freidora
        title: freidora
  - if:
    - condition: device
      device_id: 27e1fc532d9f196a308bc1db06e22996
      domain: device_tracker
      entity_id: device_tracker.charliemovil
      type: is_home
    then:
    - service: notify.mobile_app_charliemovil
      data:
        message: la freidora ha terminado
  - if:
    - condition: device
      device_id: 7287308823800457f045bbc7f59fa2a4
      domain: device_tracker
      entity_id: device_tracker.marcomovil
      type: is_home
    then:
    - service: notify.mobile_app_marcomovil
      data:
        message: la freidora ha terminado
  - if:
    - condition: device
      device_id: 1434f347839ffff0fa9439a0f56dae34
      domain: device_tracker
      entity_id: device_tracker.chekyphone
      type: is_home
    then:
    - service: notify.mobile_app_chekyphone
      data:
        message: la freidora ha terminado
  mode: single
- id: '1683545803571'
  alias: 'Freidora: menea la comida'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.xiaomi_airfryer_turn_pot
  condition: []
  action:
  - if:
    - condition: device
      device_id: 57b12107744bb3c305458a2f262baf92
      domain: device_tracker
      entity_id: device_tracker.pixel_4archeky
      type: is_home
    then:
    - service: notify.mobile_app_pixel_4archeky
      data:
        message: menea la comida
        title: freidora
  - if:
    - condition: device
      device_id: 27e1fc532d9f196a308bc1db06e22996
      domain: device_tracker
      entity_id: device_tracker.charliemovil
      type: is_home
    then:
    - service: notify.mobile_app_charliemovil
      data:
        message: menea la comida
        title: Freidora
  - if:
    - condition: device
      device_id: 7287308823800457f045bbc7f59fa2a4
      domain: device_tracker
      entity_id: device_tracker.marcomovil
      type: is_home
    then:
    - service: notify.mobile_app_marcomovil
      data:
        message: menea la comida
        title: Freidora
  mode: single
- id: '1685428500412'
  alias: 'luz despacho: apagar dormitorio'
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: b3966c17c5c785d6fcbe3d32b741b298
    entity_id: light.yeelight_color_0x458eb33
    domain: light
  condition: []
  action:
  - type: turn_off
    device_id: 2359fb0bbae57df7d4c78fa5b1a8e86c
    entity_id: light.yeelight_color_0x330dc29
    domain: light
  mode: single
- id: '1685428768065'
  alias: 'luz dormitorio: apagar despacho'
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 2359fb0bbae57df7d4c78fa5b1a8e86c
    entity_id: light.yeelight_color_0x330dc29
    domain: light
  condition: []
  action:
  - type: turn_off
    device_id: b3966c17c5c785d6fcbe3d32b741b298
    entity_id: light.yeelight_color_0x458eb33
    domain: light
  mode: single
