- id: '1673686532506'
  alias: 'Home Assistant Iniciado '
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.dashboard_mushroom
    metadata: {}
  - device_id: 65122e093172c7ed7dbecd2ab881f12b
    domain: mobile_app
    type: notify
    title: Home assistant
    message: 'Iniciado '
  - service: switch.turn_off
    target:
      entity_id: switch.transmission_interruptor
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: switch.turn_on
    target:
      entity_id:
      - switch.transmission_interruptor
      device_id: []
      area_id: []
    data: {}
  mode: single
- id: '1687987871735'
  alias: 'Roborock: mapa off'
  description: apaga la "cámara" cuando está en la base
  trigger:
  - platform: device
    device_id: f90f267269373f33820eada09da4a0b0
    domain: vacuum
    entity_id: vacuum.roborock_s6_pure
    type: docked
  condition: []
  action:
  - service: camera.turn_off
    data: {}
    target:
      entity_id: camera.roborock_s6_pure
  mode: single
- id: '1691147866863'
  alias: 'TabCheky: carga inteligente '
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /30
    enabled: false
  - platform: state
    entity_id:
    - sensor.tabcheky_battery_level
  condition: []
  action:
  - alias: Tabcheky>80
    if:
    - type: is_battery_level
      condition: device
      device_id: 819a0cd04755a087b62361e40241b5ec
      entity_id: 72b38117b447ee77e4be90abecae90a7
      domain: sensor
      above: 80
    then:
    - service: switch.turn_off
      data: {}
      target:
        entity_id:
        - switch.ladron_socket_2
  - alias: Tabcheky<70
    if:
    - type: is_battery_level
      condition: device
      device_id: 819a0cd04755a087b62361e40241b5ec
      entity_id: 72b38117b447ee77e4be90abecae90a7
      domain: sensor
      below: 70
    then:
    - service: switch.turn_on
      data: {}
      target:
        entity_id:
        - switch.ladron_socket_2
  mode: restart
- id: '1695899000007'
  alias: LarkCheky Always On
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: da6fed41428ccca872239decb6c90e28
    entity_id: 1540e7f2e75d995ece933bcc92af3951
    domain: switch
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: homeassistant
    event: start
  - platform: device
    type: turned_off
    device_id: 5e8d19dcd2cb8faabfb561b154922f74
    entity_id: 66b20acede38ba290ed0cc71d4c133cc
    domain: switch
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - type: turn_on
    device_id: da6fed41428ccca872239decb6c90e28
    entity_id: 1540e7f2e75d995ece933bcc92af3951
    domain: switch
  - type: turn_on
    device_id: 5e8d19dcd2cb8faabfb561b154922f74
    entity_id: 66b20acede38ba290ed0cc71d4c133cc
    domain: switch
  mode: single
- id: '1698489590281'
  alias: Casa vacía
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - zone.home
    for:
      hours: 0
      minutes: 5
      seconds: 5
    below: 1
  condition: []
  action:
  - device_id: 65122e093172c7ed7dbecd2ab881f12b
    domain: mobile_app
    type: notify
    message: vacía
    title: Casa
  - service: light.turn_off
    data: {}
    target:
      area_id:
      - despacho
      - dormitorio
      - pasillo
      - salon
  - service: remote.turn_off
    data: {}
    target:
      area_id: salon
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.caldera
  - service: light.turn_off
    data: {}
    target:
      area_id:
      - despacho
      - dormitorio
      - pasillo
      - salon
  - service: homeassistant.turn_off
    target:
      area_id:
      - cocina
      - despacho
      - dormitorio
      - salon
    data: {}
  - service: climate.turn_off
    target:
      area_id:
      - cocina
      - dormitorio
    data: {}
  - device_id: f90f267269373f33820eada09da4a0b0
    domain: vacuum
    entity_id: 8be8688f6195fef0a72213fee4608906
    type: clean
  mode: single
- id: '1701110449652'
  alias: Luz dormitorio toggle
  description: '

    '
  trigger:
  - type: turned_on
    platform: device
    device_id: a7d977c7678c671a77dbc66e88edf3b5
    entity_id: 27576fc5181f3d5141f35984490826c9
    domain: binary_sensor
  condition: []
  action:
  - if:
    - condition: or
      conditions:
      - condition: state
        entity_id: light.yeelight_color_0x330dc29
        state: 'on'
      - condition: state
        state: 'on'
        entity_id: light.dormitorio
    then:
    - service: light.turn_off
      data: {}
      target:
        area_id: dormitorio
    else:
    - service: light.turn_on
      data:
        kelvin: 6500
      target:
        area_id: dormitorio
  mode: single
- id: '1701362213795'
  alias: termostato daily off
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: climate.turn_off
    data: {}
    target:
      area_id: cocina
  - device_id: 4cdc09571595831740eb92760584bb20
    domain: climate
    entity_id: 6883f7d7ef018d8f46875a7ecf83c38f
    type: set_hvac_mode
    hvac_mode: 'off'
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.caldera
  - device_id: 65122e093172c7ed7dbecd2ab881f12b
    domain: mobile_app
    type: notify
    title: Termostato
    message: 'Apagado diario '
  mode: queued
  max: 10
- id: '1701364196838'
  alias: termostato auto
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.temperatura_termostato_temperatura
  - platform: state
    entity_id:
    - input_number.temperatura_deseada
  - platform: state
    entity_id:
    - input_boolean.caldera
  - platform: state
    entity_id:
    - sensor.caldera_accion_hvac
  - platform: state
    entity_id:
    - climate.caldera_termostato
  condition:
  - condition: state
    entity_id: climate.caldera_termostato
    state: heat
  action:
  - if:
    - alias: Cuando la temperatura esté por encima de la deseada
      condition: numeric_state
      entity_id: sensor.temperatura_termostato_temperatura
      above: input_number.temperatura_deseada
    then:
    - service: climate.set_temperature
      data:
        temperature: 7
      target:
        entity_id: climate.caldera_termostato
      alias: poner en espera
    else:
    - service: climate.set_temperature
      data:
        temperature: 30
      target:
        entity_id: climate.caldera_termostato
      alias: Calentar
  mode: restart
- id: '1701364758711'
  alias: termostato caldera helper
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.caldera
  condition: []
  action:
  - if:
    - condition: state
      entity_id: input_boolean.caldera
      state: 'on'
    then:
    - device_id: 4cdc09571595831740eb92760584bb20
      domain: climate
      entity_id: 6883f7d7ef018d8f46875a7ecf83c38f
      type: set_hvac_mode
      hvac_mode: heat
    else:
    - device_id: 4cdc09571595831740eb92760584bb20
      domain: climate
      entity_id: 6883f7d7ef018d8f46875a7ecf83c38f
      type: set_hvac_mode
      hvac_mode: 'off'
  mode: single
- id: '1701965983999'
  alias: 'Luz despacho toggle '
  description: '

    '
  trigger:
  - type: turned_on
    platform: device
    device_id: cac8eaf37904039a66158f6e5efb4d69
    entity_id: 835711241331f82a1a83e78e67dd19f1
    domain: binary_sensor
  condition: []
  action:
  - if:
    - condition: or
      conditions:
      - condition: state
        state: 'on'
        entity_id: light.despacho
      - condition: state
        state: 'on'
        entity_id: light.yeelight_color_0x458eb33
    then:
    - service: light.turn_off
      data: {}
      target:
        area_id:
        - despacho
    else:
    - service: light.turn_on
      data:
        brightness_step_pct: 100
        kelvin: 6500
      target:
        entity_id: light.despacho
  mode: single
- id: '1701967185337'
  alias: 'Luz pasillo auto '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presencia_pasillo
  - platform: state
    entity_id:
    - light.gateway_light_7811dcfab2fc
    to: 'on'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.presencia_pasillo
      state: 'on'
    then:
    - service: light.turn_on
      target:
        area_id: pasillo
      data:
        kelvin: 6500
        brightness_pct: 100
    else:
    - service: light.turn_off
      target:
        area_id: pasillo
      data: {}
  mode: restart
- id: '1701967702141'
  alias: 'Luz dormitorio auto '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presencia_dormitorio
  - platform: state
    entity_id:
    - light.dormitorio
    to: 'on'
    enabled: false
  - platform: state
    entity_id:
    - light.yeelight_color_0x330dc29
    to: 'on'
    enabled: false
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id: dormitorio
    data: {}
    enabled: false
  - if:
    - condition: and
      conditions:
      - condition: state
        state: 'on'
        entity_id: binary_sensor.presencia_dormitorio
      - condition: time
        after: sensor.sun_next_dawn
        before: sensor.sun_next_midnight
        enabled: false
    then:
    - if:
      - condition: time
        after: sensor.sun_next_dawn
        before: 00:00:00
        weekday:
        - mon
        - tue
        - wed
        - thu
        - sun
      then:
      - service: light.turn_on
        target:
          area_id: dormitorio
        data:
          kelvin: 6500
          brightness_pct: 100
      else:
      - service: light.turn_on
        target:
          entity_id: light.yeelight_color_0x330dc29
        data:
          kelvin: 2000
          brightness_pct: 100
    else:
    - delay:
        hours: 0
        minutes: 3
        seconds: 0
        milliseconds: 0
    - service: light.turn_off
      target:
        area_id:
        - dormitorio
      data: {}
    enabled: true
  mode: restart
- id: '1701968174075'
  alias: Luz salón auto ON
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presencia_salon
    to: 'on'
  - platform: sun
    event: sunset
    offset: -0:05:00
  - platform: sun
    event: sunrise
    offset: '1:00:00'
  condition:
  - condition: and
    conditions:
    - condition: numeric_state
      entity_id: zone.home
      above: 0
    - condition: state
      entity_id: binary_sensor.presencia_salon
      state: 'on'
    - condition: or
      conditions:
      - condition: numeric_state
        entity_id: sensor.presencia_salon_iluminancia
        below: 20
      - condition: sun
        before: sunrise
        after: sunset
        before_offset: '1:00:00'
        after_offset: '-1:00:00'
  action:
  - if:
    - condition: sun
      before: sunrise
      after: sunset
      before_offset: '1:00:00'
      after_offset: -0:30:00
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.salon
  mode: restart
- id: '1701992925702'
  alias: Luz despacho auto ON
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.movimiento_despacho
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: sun
      before: sunrise
      after: sunset
      before_offset: '1:00:00'
      after_offset: -0:30:00
    - condition: numeric_state
      entity_id: zone.home
      above: 0
    - condition: state
      entity_id: light.despacho
      state: 'off'
    - condition: state
      entity_id: light.yeelight_color_0x458eb33
      state: 'off'
  action:
  - service: light.turn_on
    target:
      entity_id: light.despacho
    data:
      kelvin: 6500
      brightness_step_pct: 100
  mode: restart
- id: '1702054714830'
  alias: luz salón auto OFF
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presencia_salon
    for:
      hours: 0
      minutes: 0
      seconds: 0
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.presencia_salon
    for:
      hours: 0
      minutes: 0
      seconds: 10
    to: 'off'
  - platform: state
    entity_id:
    - light.salon
  condition: []
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.presencia_salon
      state: 'off'
    then:
    - if:
      - condition: state
        entity_id: media_player.tv_del_salon
        state: playing
      then:
      - service: media_player.media_pause
        target:
          area_id: salon
        data: {}
      - delay:
          hours: 0
          minutes: 5
          seconds: 0
          milliseconds: 0
      else:
      - delay:
          hours: 0
          minutes: 1
          seconds: 5
          milliseconds: 0
    - service: light.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: light.salon
        area_id: salon
    else:
    - if:
      - condition: and
        conditions:
        - condition: state
          entity_id: binary_sensor.presencia_salon
          state: 'on'
        - condition: not
          conditions:
          - condition: state
            entity_id: media_player.tv_del_salon
            state: playing
      then:
      - service: media_player.media_play
        target:
          entity_id: media_player.tv_del_salon
        data: {}
  mode: restart
- id: '1702059143983'
  alias: Luz despacho auto OFF
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.movimiento_despacho
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
    - binary_sensor.192_168_68_212
    to:
  - platform: state
    entity_id:
    - light.despacho
    to: 'on'
  - platform: state
    entity_id:
    - light.yeelight_color_0x458eb33
    to: 'on'
  condition: []
  action:
  - if:
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.movimiento_despacho
        state: 'off'
      - condition: state
        entity_id: binary_sensor.192_168_68_212
        state: 'off'
        enabled: true
      - condition: state
        entity_id: button.pcck_suspender
        state: unavailable
        for:
          hours: 0
          minutes: 0
          seconds: 0
    then:
    - service: light.turn_off
      target:
        area_id: despacho
      data: {}
  mode: restart
- id: '1702063814054'
  alias: update sensors
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /3
  - platform: time_pattern
    seconds: /9
    enabled: false
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id:
      - binary_sensor.192_168_68_212
      - binary_sensor.192_168_68_200
      - sensor.temperatura_termostato_temperatura
      - binary_sensor.movimiento_pasillo_movimiento
  mode: single
- id: '1702574744141'
  alias: Navidad
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.enchufe_2_interruptor
    to: 'on'
    for:
      hours: 0
      minutes: 3
      seconds: 50
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id:
      - light.enchufe_2_interruptor
      device_id: []
      area_id: []
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 50
  - service: light.toggle
    target:
      entity_id:
      - light.enchufe_2_interruptor
      device_id: []
      area_id: []
    data: {}
  mode: single
- id: '1702925270265'
  alias: Roborock update map
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.actualizar_mapa
  condition: []
  action:
  - service: homeassistant.update_entity
    target:
      entity_id: camera.roborock_s6_pure
    data: {}
  - service: notify.mobile_app_chekyphone
    data:
      message: Ghj
  mode: single
- id: '1703711375036'
  alias: 'Apagado general '
  description: ''
  trigger:
  - platform: device
    type: changed_states
    device_id: b3966c17c5c785d6fcbe3d32b741b298
    entity_id: 8fabd1a7883fa0fffa3d302d529681a3
    domain: light
  - platform: device
    type: changed_states
    device_id: 2359fb0bbae57df7d4c78fa5b1a8e86c
    entity_id: 85f79200ed639ba2d5afd39d96214da9
    domain: light
  - platform: state
    entity_id:
    - light.despacho
  - platform: state
    entity_id:
    - light.yeelight_color_0x458eb33
  - platform: state
    entity_id:
    - light.dormitorio
  - platform: state
    entity_id:
    - light.yeelight_color_0x330dc29
  - platform: state
    entity_id:
    - light.gateway_light_7811dcfab2fc
  - platform: state
    entity_id:
    - light.salon
  - platform: state
    entity_id:
    - input_boolean.caldera
  - platform: state
    entity_id:
    - climate.caldera_termostato
  - platform: state
    entity_id:
    - light.enchufe_2_interruptor
  - platform: state
    entity_id:
    - input_boolean.caldera
  condition:
  - condition: numeric_state
    entity_id: zone.home
    below: 1
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: homeassistant.turn_off
    target:
      area_id:
      - dormitorio
      - salon
      - cocina
      - despacho
      entity_id:
      - light.centralita_light
      - light.gateway_light_7811dcfab2fc
    data: {}
  - service: climate.turn_off
    target:
      entity_id: climate.caldera_termostato
    data: {}
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.caldera
    data: {}
  mode: restart
- id: '1704871966321'
  alias: Pcck ON
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.192_168_68_200
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.192_168_68_200
    to: 'off'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.192_168_68_200
      state: 'on'
    then:
    - service: homeassistant.turn_on
      target:
        entity_id: switch.ladron_usb_1
      data: {}
    else:
    - service: homeassistant.turn_off
      target:
        entity_id: switch.ladron_usb_1
      data: {}
  mode: single
- id: '1705070087247'
  alias: Llegando a casa marco
  description: ''
  trigger:
  - platform: zone
    entity_id: person.marco
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_chekyphone
    data:
      message: Marco está llegando a casa
  mode: single
- id: '1705070113841'
  alias: 'Llegando a casa chespin '
  description: ''
  trigger:
  - platform: zone
    entity_id: person.chespin
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_chekyphone
    data:
      message: Chespin está llegando a casa
  mode: single
- id: '1705565177009'
  alias: 'Roborock: Limpieza programada'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.hora_limpieza
  condition: []
  action:
  - device_id: f90f267269373f33820eada09da4a0b0
    domain: vacuum
    entity_id: 8be8688f6195fef0a72213fee4608906
    type: clean
  mode: single
