
# Loads default set of integrations. Do not remove.
default_config:

my:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# http integration
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 0.0.0.0
    - 192.168.8.201
    - ha.carcheky.com

# google_assistant integration
google_assistant:
  project_id: home-assistant-raspiserver
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - vacuum
    - group
    - scene
    - climate
  # entity_config:
  #   input_boolean.default_dashboard:
  #     expose: false
  #   input_select.default_dashboard:
  #     expose: false
  #   sensor.temperature_humidity_sensor_fb23_temperature:
  #     expose: false
  #   sensor.temperature_humidity_sensor_f85c_temperature:
  #     expose: false
  #   sensor.temperature_humidity_sensor_2d7c_temperature:
  #     expose: false
  #   sensor.temperature_humidity_sensor_fb23_humidity:
  #     expose: false
  #   sensor.temperature_humidity_sensor_f85c_humidity:
  #     expose: false
  #   sensor.temperature_humidity_sensor_2d7c_humidity:
  #     expose: false

# wake on lan integration
switch:
  - platform: wake_on_lan
    mac: !secret wake_on_lan_mac
    name: PCCK

# pc online
binary_sensor:  
  - platform: ping
    host: 192.168.68.200
    name: PCCK
  - platform: template
    sensors:
      desktop_online:
        friendly_name: "PCCK Desktop Online"
        delay_off:
          minutes: 5
        value_template: >-
          {{ states('binary_sensor.pcck')}}
  - platform: ping
    host: 192.168.68.124
    name: cmartinezv-lpt
  - platform: template
    sensors:
      desktop_online2:
        friendly_name: "cmartinezv-lpt Desktop Online"
        delay_off:
          minutes: 5
        value_template: >-
          {{ states('binary_sensor.cmartinezv-lpt')}}

# sdistant integration
homeassistant:
  name: Drona
  unit_system: metric
  currency: EUR
  country: ES
  time_zone: "Europe/Madrid"
  external_url: "https://ha.carcheky.com"
  internal_url: "http://192.168.68.201:8123"

# zigbee integration
zha:
  zigpy_config:
    ezsp_config:
      CONFIG_APS_UNICAST_MESSAGE_COUNT: 12
      CONFIG_SOURCE_ROUTE_TABLE_SIZE: 16
      CONFIG_ADDRESS_TABLE_SIZE: 8

zha_toolkit:

logger:
  default: warn
  # logs:
  #   custom_components.zha_toolkit: error
  #   zigpy: error
  #   zigpy_zcl: error
  #   homeassistant.loader: error

# xiaomi_cloud_map_extractor
camera:  
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    scan_interval: 30
    map_transformation:
      scale: 1
      trim: 
        top: 20
        left: 10
        bottom: 15
        right: 30
    # attributes:
    #   - calibration_points
    country: "sg"
    name: "Roborock S6 Pure"
    attributes:
      - calibration_points
      - charger
      - cleaned_rooms
      - country
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - ignored_obstacles
      - obstacles_with_photo
      - ignored_obstacles_with_photo
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - vacuum_room_name
      - walls
      - zones
    # auto_update: false
    # store_map_raw: true
    # store_map_image: true
    
# xiaomi_cloud_map_extractor END

# xiaomi_aqara:
#   discovery_retry: 20
#   gateways:
#     - key: !secret xiaomi_key_gateway
#       host: 192.168.68.104
#       mac: !secret xiaomi_mac_gateway