
# Loads default set of integrations. Do not remove.
default_config:
device_sun_light_trigger:
my:
bluetooth:
api:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# http integration
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 0.0.0.0/0
    - ::1

# google_assistant integration
google_assistant:
  project_id: home-assistant-raspiserver
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - vacuum
    - group
    # - scene
    # - climate
  # entity_config:
  #   input_boolean.default_dashboard:
  #     expose: false
  #   input_select.default_dashboard:
  #     expose: false
  #   sensor.temperature_humidity_sensor_fb23_temperature:
  #     expose: false
  #   sensor.temperature_humidity_sensor_f85c_temperature:
  #     expose: false
  #   sensor.temperature_humidity_sensor_2d7c_temperature:
  #     expose: false
  #   sensor.temperature_humidity_sensor_fb23_humidity:
  #     expose: false
  #   sensor.temperature_humidity_sensor_f85c_humidity:
  #     expose: false
  #   sensor.temperature_humidity_sensor_2d7c_humidity:
  #     expose: false

# wake on lan integration
switch:
  - platform: wake_on_lan
    mac: !secret wake_on_lan_mac_pcck
    name: Wake PCCK 

# homeassistant integration
homeassistant:
  name: Drona
  unit_system: metric
  currency: EUR
  country: ES
  time_zone: "Europe/Madrid"
  external_url: !secret external_url
  internal_url: !secret internal_url

# xiaomi_cloud_map_extractor
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    scan_interval: 900
    map_transformation:
      scale: 1
      trim:
        top: 20
        left: 10
        bottom: 15
        right: 30
    # attributes:
    #   - calibration_points
    country: "sg"
    name: "Roborock S6 Pure"
    attributes:
      - calibration_points
      - charger
      - cleaned_rooms
      - country
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - ignored_obstacles
      - obstacles_with_photo
      - ignored_obstacles_with_photo
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - vacuum_room_name
      - walls
      - zones
    # auto_update: true
    store_map_raw: true
    store_map_image: true
# xiaomi_cloud_map_extractor END

zha:
  custom_quirks_path: /config/custom_zha_quirks
  database_path: /config/zigbee.db 
  enable_quirks: true

logger:
  default: warn
  logs:
    homeassistant.components.zha.core.cluster_handlers: info
    # bellows.ezsp: info
    # bellows.zigbee.application: info
    # custom_components.zha_toolkit: info
    # zigpy_deconz.api: info
    # zigpy_deconz.zigbee.application: info
    # zigpy_xbee.api: info
    # zigpy_xbee.zigbee.application: info
    # zigpy_zcl: info
    # zigpy_zigate: info
    # zigpy_znp: info
    # zigpy: info
    # zhaquirks: info
    # homeassistant.components.zha: info
    # homeassistant.core: info
    # homeassistant.loader: info


# # Example configuration.yaml entry
# sensor:
#   - platform: mqtt_room
#     device_id: 123testid
#     state_topic: "espresense/devices/123testid"