- id: '1674520232167'
  name: Dormitorio fade off
  entities:
    light.yeelight_color_0x330dc29:
      min_color_temp_kelvin: 1700
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 588
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Night Mode
      - Date Night
      - Movie
      - Sunrise
      - Sunset
      - Romance
      - Happy Birthday
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Home
      - Candle Flicker
      - Slow Temp
      - Stop
      supported_color_modes:
      - color_temp
      - hs
      - rgb
      flowing: true
      music_mode: false
      friendly_name: Luz dormitorio
      supported_features: 44
      color_mode: color_temp
      brightness: 115
      color_temp_kelvin: 2923
      color_temp: 342
      hs_color:
      - 27.957
      - 59.028
      rgb_color:
      - 255
      - 174
      - 104
      xy_color:
      - 0.504
      - 0.384
      effect: Sunset
      state: 'on'
  icon: mdi:lightbulb-night
  metadata: {}
- id: '1677683268735'
  name: Apagar Salón
  entities:
    media_player.altavoz_salon:
      device_class: speaker
      friendly_name: Altavoz Salón
      supported_features: 152461
      state: 'off'
    climate.aire:
      hvac_modes:
      - 'off'
      - cool
      - heat
      - dry
      - fan_only
      min_temp: 16
      max_temp: 31
      target_temp_step: 1
      fan_modes:
      - low
      - mid
      - high
      - auto
      current_temperature: 27
      temperature: 25
      fan_mode: low
      friendly_name: Aire
      supported_features: 9
      state: 'off'
    switch.luz_salon_socket:
      device_class: outlet
      friendly_name: Luz salon Socket
      state: 'off'
    light.luz_salon_socket:
      supported_color_modes:
      - onoff
      friendly_name: Luz salon
      supported_features: 0
      state: 'off'
  icon: mdi:monitor-speaker-off
  metadata:
    climate.aire:
      entity_only: true
- id: '1677683346686'
  name: Despacho apagado
  entities:
    media_player.altavoz_dormitorio:
      device_class: speaker
      friendly_name: Altavoz despacho
      supported_features: 152461
      state: 'off'
    light.yeelight_color_0x458eb33:
      min_color_temp_kelvin: 1700
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 588
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Night Mode
      - Date Night
      - Movie
      - Sunrise
      - Sunset
      - Romance
      - Happy Birthday
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Home
      - Candle Flicker
      - Tea Time
      - Slow Temp
      - Stop
      supported_color_modes:
      - color_temp
      - hs
      - rgb
      effect:
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      flowing: false
      music_mode: false
      friendly_name: Luz despacho escritorio
      supported_features: 44
      state: 'off'
    light.despacho:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 7042
      min_mireds: 142
      max_mireds: 500
      effect_list:
      - colorloop
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - xy
      effect:
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      entity_id:
      - light.despacho_1_luz
      - light.despacho_2_luz
      - light.despacho_3
      icon: mdi:lightbulb-group
      friendly_name: Luz despacho
      supported_features: 44
      state: 'off'
  icon: mdi:monitor-speaker-off
  metadata:
    light.despacho:
      entity_only: true
- id: '1679915578111'
  name: Luces apagadas
  entities:
    light.yeelight_color_0x330dc29:
      min_color_temp_kelvin: 1700
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 588
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Night Mode
      - Date Night
      - Movie
      - Sunrise
      - Sunset
      - Romance
      - Happy Birthday
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Home
      - Candle Flicker
      - Slow Temp
      - Stop
      supported_color_modes:
      - color_temp
      - hs
      - rgb
      friendly_name: Luz dormitorio
      supported_features: 44
      state: unavailable
    light.yeelight_color_0x458eb33:
      min_color_temp_kelvin: 1700
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 588
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Night Mode
      - Date Night
      - Movie
      - Sunrise
      - Sunset
      - Romance
      - Happy Birthday
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Home
      - Candle Flicker
      - Slow Temp
      - Stop
      supported_color_modes:
      - color_temp
      - hs
      - rgb
      flowing: false
      music_mode: false
      friendly_name: Luz despacho
      supported_features: 44
      state: 'off'
    switch.luz_socket:
      device_class: outlet
      friendly_name: luz Socket
      state: 'off'
    light.socket:
      supported_color_modes:
      - onoff
      friendly_name: Luz salón
      supported_features: 0
      state: 'off'
  icon: mdi:string-lights-off
  metadata: {}
- id: '1698489745784'
  name: Casa vacía
  entities:
    light.yeelight_color_0x458eb33:
      min_color_temp_kelvin: 1700
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 588
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Night Mode
      - Date Night
      - Movie
      - Sunrise
      - Sunset
      - Romance
      - Happy Birthday
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Home
      - Candle Flicker
      - Tea Time
      - Slow Temp
      - Stop
      supported_color_modes:
      - color_temp
      - hs
      - rgb
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      effect:
      flowing: false
      music_mode: false
      friendly_name: Luz despacho escritorio
      supported_features: 44
      state: 'off'
    light.ewelink_ck_bl702_al_01_7009_z102lg03_1_light:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 7042
      min_mireds: 142
      max_mireds: 500
      effect_list:
      - colorloop
      supported_color_modes:
      - color_temp
      - xy
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      effect:
      off_with_transition: false
      off_brightness: 254
      friendly_name: Luz despacho 1 Luz
      supported_features: 44
      state: 'off'
    light.ewelink_ck_bl702_al_01_7009_z102lg03_1_light_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 7042
      min_mireds: 142
      max_mireds: 500
      effect_list:
      - colorloop
      supported_color_modes:
      - color_temp
      - xy
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      effect:
      off_with_transition: false
      off_brightness: 254
      friendly_name: Luz despacho 2 Luz
      supported_features: 44
      state: 'off'
    light.yeelight_color_0x330dc29:
      min_color_temp_kelvin: 1700
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 588
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Night Mode
      - Date Night
      - Movie
      - Sunrise
      - Sunset
      - Romance
      - Happy Birthday
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Home
      - Candle Flicker
      - Tea Time
      - Slow Temp
      - Stop
      supported_color_modes:
      - color_temp
      - hs
      - rgb
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      effect:
      flowing: false
      music_mode: false
      friendly_name: Luz mesita
      supported_features: 44
      state: 'off'
    light.ewelink_ck_bl702_al_01_7009_z102lg03_1_light_3:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 7042
      min_mireds: 142
      max_mireds: 500
      effect_list:
      - colorloop
      supported_color_modes:
      - color_temp
      - xy
      friendly_name: Luz dormitorio 1 Luz
      supported_features: 44
      state: unavailable
    light.ewelink_ck_bl702_al_01_7009_z102lg03_1_light_4:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 7042
      min_mireds: 142
      max_mireds: 500
      effect_list:
      - colorloop
      supported_color_modes:
      - color_temp
      - xy
      friendly_name: Luz dormitorio 2 Luz
      supported_features: 44
      state: unavailable
    light.ewelink_ck_bl702_al_01_7009_z102lg03_1_light_5:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 7042
      min_mireds: 142
      max_mireds: 500
      effect_list:
      - colorloop
      supported_color_modes:
      - color_temp
      - xy
      friendly_name: Luz dormitorio 3 Luz
      supported_features: 44
      state: unavailable
    switch.enchufe_zb_3_luz_salon_switch:
      friendly_name: Enchufe ZB 3 - Luz Salón Interruptor
      state: 'off'
    light.enchufe_zb_3_luz_salon_switch:
      supported_color_modes:
      - onoff
      color_mode:
      friendly_name: Enchufe ZB 3 - Luz Salón Interruptor
      supported_features: 0
      state: 'off'
    light.wifi_gu10_despacho:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: Luz despacho 3
      supported_features: 0
      state: 'off'
    light.gateway_light_7811dcfab2fc:
      supported_color_modes:
      - hs
      color_mode:
      brightness:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: Centralita
      supported_features: 0
      state: 'off'
    media_player.altavoz_dormitorio:
      device_class: speaker
      friendly_name: Altavoz despacho
      supported_features: 152461
      state: 'off'
    media_player.altavoz_cocina:
      device_class: speaker
      friendly_name: Altavoz Dormitorio
      supported_features: 152461
      state: 'off'
    media_player.altavoz_salon:
      device_class: speaker
      friendly_name: Altavoz Salón
      supported_features: 152461
      state: 'off'
  metadata: {}
  icon: mdi:home-export-outline
- id: '1700501760401'
  name: Default dashboard
  entities:
    input_select.default_dashboard:
      options:
      - lovelace
      - dashboard-roborock
      - mushroom-strategy
      - dashboard-tests
      - dashboard-drona
      - refresh
      editable: true
      friendly_name: Default Dashboard
      state: dashboard-drona
  metadata:
    input_select.default_dashboard:
      entity_only: true
- id: '1702404813013'
  name: Despacho gamming
  entities:
    light.despacho_1_luz:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 7042
      min_mireds: 142
      max_mireds: 500
      effect_list:
      - colorloop
      supported_color_modes:
      - color_temp
      - xy
      color_mode: xy
      brightness: 54
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 224.64
      - 98.039
      rgb_color:
      - 5
      - 69
      - 255
      xy_color:
      - 0.137
      - 0.065
      effect:
      off_with_transition: false
      off_brightness:
      friendly_name: despacho 1 Luz
      supported_features: 44
      state: 'on'
    light.despacho_2_luz:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 7042
      min_mireds: 142
      max_mireds: 500
      effect_list:
      - colorloop
      supported_color_modes:
      - color_temp
      - xy
      color_mode: xy
      brightness: 140
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 357.414
      - 90.98
      rgb_color:
      - 255
      - 23
      - 33
      xy_color:
      - 0.689
      - 0.298
      effect:
      off_with_transition: false
      off_brightness:
      friendly_name: despacho 2 Luz
      supported_features: 44
      state: 'on'
    light.despacho_3:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      color_mode: hs
      brightness: 84
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 355
      - 89
      rgb_color:
      - 255
      - 28
      - 46
      xy_color:
      - 0.676
      - 0.295
      friendly_name: Luz despacho 3
      supported_features: 0
      state: 'on'
    light.yeelight_color_0x458eb33:
      min_color_temp_kelvin: 1700
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 588
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Night Mode
      - Date Night
      - Movie
      - Sunrise
      - Sunset
      - Romance
      - Happy Birthday
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Home
      - Candle Flicker
      - Tea Time
      - Slow Temp
      - Stop
      supported_color_modes:
      - color_temp
      - hs
      - rgb
      color_mode: rgb
      brightness: 120
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 233.86
      - 84.314
      rgb_color:
      - 40
      - 62
      - 255
      xy_color:
      - 0.146
      - 0.068
      effect:
      flowing: 0
      music_mode: false
      friendly_name: Luz despacho escritorio
      supported_features: 44
      state: 'on'
  icon: mdi:axe-battle
  metadata:
    light.despacho_1_luz:
      entity_only: true
    light.despacho_2_luz:
      entity_only: true
    light.despacho_3:
      entity_only: true
    light.yeelight_color_0x458eb33:
      entity_only: true
- id: '1702406048688'
  name: Despacho trabajo
  entities:
    light.despacho_1_luz:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 7042
      min_mireds: 142
      max_mireds: 500
      effect_list:
      - colorloop
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 254
      color_temp_kelvin: 7042
      color_temp: 142
      hs_color:
      - 239.562
      - 5.378
      rgb_color:
      - 241
      - 241
      - 255
      xy_color:
      - 0.313
      - 0.314
      effect:
      off_with_transition: false
      off_brightness:
      friendly_name: despacho 1 Luz
      supported_features: 44
      state: 'on'
    light.despacho_2_luz:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 7042
      min_mireds: 142
      max_mireds: 500
      effect_list:
      - colorloop
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 254
      color_temp_kelvin: 7042
      color_temp: 142
      hs_color:
      - 239.562
      - 5.378
      rgb_color:
      - 241
      - 241
      - 255
      xy_color:
      - 0.313
      - 0.314
      effect:
      off_with_transition: false
      off_brightness:
      friendly_name: despacho 2 Luz
      supported_features: 44
      state: 'on'
    light.despacho_3:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 6410
      color_temp: 156
      hs_color:
      - 41.14
      - 2.841
      rgb_color:
      - 255
      - 252
      - 247
      xy_color:
      - 0.329
      - 0.334
      friendly_name: Luz despacho 3
      supported_features: 0
      state: 'on'
    light.yeelight_color_0x458eb33:
      min_color_temp_kelvin: 1700
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 588
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Night Mode
      - Date Night
      - Movie
      - Sunrise
      - Sunset
      - Romance
      - Happy Birthday
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Home
      - Candle Flicker
      - Tea Time
      - Slow Temp
      - Stop
      supported_color_modes:
      - color_temp
      - hs
      - rgb
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 6535
      color_temp: 153
      hs_color:
      - 54.768
      - 1.6
      rgb_color:
      - 255
      - 254
      - 250
      xy_color:
      - 0.326
      - 0.333
      effect:
      flowing: false
      music_mode: false
      friendly_name: Luz despacho escritorio
      supported_features: 44
      state: 'on'
  icon: mdi:briefcase
  metadata:
    light.despacho_1_luz:
      entity_only: true
    light.despacho_2_luz:
      entity_only: true
    light.despacho_3:
      entity_only: true
    light.yeelight_color_0x458eb33:
      entity_only: true
