services:

# homeassistant http://localhost:8123
  homeassistant:
    # image: "homeassistant/home-assistant:stable"
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    privileged: true
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:homeassistant-hacs
    volumes:
      - ./volumes/ha-config:/config
      - /run/dbus:/run/dbus:ro # bluethooth
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    cap_add:
      - NET_ADMIN
      

# mqtt
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: always
    network_mode: host
    user: 1000:1000
    # ports:
    #   - 1883:1883
    #   - 9001:9001
    volumes:
      # - ./volumes/mqtt-config:/mosquitto
      - ./volumes/mqtt-config/config:/mosquitto/config
      - ./volumes/mqtt-config/data:/mosquitto/data
      - ./volumes/mqtt-config/log:/mosquitto/log
    cap_add:
      - NET_ADMIN
      

