services:
  roomassistant:
    image: mkerix/room-assistant
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ./volumes/romassistant-config:/room-assistant/config
      
