services:
  roomassistant:
    image: mkerix/room-assistant
    container_name: romassistant
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ./volumes/romassistant-config:/room-assistant/config
    cap_add:
      - NET_ADMIN
      
