services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ./volumes/esphome-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host