services:
  esphome:
    container_name: esphome
    image: esphome/esphome:latest
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      # RaspiServer reverse proxy configuration
      - TZ=${TIMEZONE}
      - ESPHOME_DASHBOARD_USE_PING=${ESPHOME_DASHBOARD_USE_PING:-true}
      - ESPHOME_LOGGING_LEVEL=${ESPHOME_LOGGING_LEVEL:-INFO}
    volumes:
      - ${VOLUMES_DIR}/esphome-config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial:/dev/serial # For USB devices
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # ESP programming device
      - /dev/ttyACM0:/dev/ttyACM0 # Alternative ESP device
    ports:
      - ${ESPHOME_PORT:-6052}:6052
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6052/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
    labels:
      # Caddy reverse proxy configuration
      - "caddy=esphome.${RASPISERVER_DOMAINS:-cckdev.es,localhost}"
      - "caddy.reverse_proxy={{upstreams 8080}}"
      - "caddy.header=/ X-Forwarded-Proto {scheme}"
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=iot-automation"
      - "raspiserver.description=ESPHome dashboard for IoT device management"
