services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: unless-stopped
    network_mode: host
    user: "${PUID:-1000}:${PGID:-1000}"
    environment:
      - TZ=${TIMEZONE}
      - MOSQUITTO_USERNAME=${MQTT_USERNAME:-}
      - MOSQUITTO_PASSWORD=${MQTT_PASSWORD:-}
    # Alternative port configuration if not using host networking:
    # ports:
    #   - ${MQTT_PORT:-1883}:1883
    #   - ${MQTT_WS_PORT:-9001}:9001
    volumes:
      - ${VOLUMES_DIR}/mqtt-config/config:/mosquitto/config
      - ${VOLUMES_DIR}/mqtt-config/data:/mosquitto/data
      - ${VOLUMES_DIR}/mqtt-config/log:/mosquitto/log
      - ${VOLUMES_DIR}/mqtt-config/ssl:/mosquitto/ssl:ro # SSL certificates
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-p", "1883", "-t", "health/check", "-m", "ping", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 64M
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=iot-messaging"
      - "raspiserver.description=MQTT broker for IoT device communication"
