services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "${UPTIME_KUMA_PORT:-3001}:3001"
    volumes:
      - ${VOLUMES_DIR}/uptime-kuma-app-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only Docker socket access
    environment:
      # RaspiServer reverse proxy configuration
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - NODE_ENV=${NODE_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      # Caddy reverse proxy configuration
      - "caddy=uptime-kuma.${RASPISERVER_DOMAINS:-cckdev.es,localhost}"
      - "caddy.reverse_proxy={{upstreams 3001}}"
      - "caddy.header=/ X-Forwarded-Proto {scheme}"
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=monitoring"
      - "raspiserver.description=Website and service uptime monitoring with alerting"

