services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "${UPTIME_KUMA_PORT:-3001}:3001"
    volumes:
      - ${VOLUMES_DIR}/uptime-kuma-app-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}

