services:
  janitorr:
    container_name: janitorr
    image: ghcr.io/schaka/janitorr:latest
    restart: unless-stopped
    user: ${PUID}:${PGID}
    volumes:
      - ${VOLUMES_DIR}/janitorr-config/:/config
      - ${VOLUMES_DIR}/janitorr-logs:/logs
      - ${MEDIA_DIR}:/media # Media library for cleanup operations
    environment:
      # RaspiServer reverse proxy configuration
      - TZ=${TIMEZONE}
      - LANG=${LOCALE:-es_ES.UTF-8}
      - LANGUAGE=${LOCALE_LANG:-es_ES:es}
      - JANITORR_LOG_LEVEL=${JANITORR_LOG_LEVEL:-info}
      # - LC_ALL=es_ES.UTF-8
    ports:
      - ${JANITORR_PORT:-8081}:8081
    healthcheck:
      test: ["CMD", "wget", "-T5", "-qO-", "http://localhost:8081/health"]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - sonarr
      - radarr
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      # Caddy reverse proxy configuration
      - "caddy=janitorr.${RASPISERVER_DOMAINS:-cckdev.es,localhost}"
      - "caddy.reverse_proxy={{upstreams 8080}}"
      - "caddy.header=/ X-Forwarded-Proto {scheme}"
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=media-maintenance"
      - "raspiserver.description=Automated media library cleanup and maintenance"
