services:
  janitorr:
    container_name: janitorr
    restart: always
    user: ${PUID}:${PGID}
    volumes:
      - ${VOLUMES_DIR}/janitorr-config/:/config
      - ${VOLUMES_DIR}/janitorr-logs:/logs
      - ${MEDIA_DIR}:/BibliotecaMultimedia
    environment:
      - LANG=es_ES.UTF-8
      - LANGUAGE=es_ES:es
      # - LC_ALL=es_ES.UTF-8
    image: ghcr.io/schaka/janitorr:develop
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8081/health | grep UP || exit 1"
      start_period: 30s
      interval: 5s
      retries: 3
