services:
  # ESTADÍSTICAS

  jellystat-db:
    image: postgres:15.2
    container_name: jellystat-db
    restart: unless-stopped
    environment:
      # RaspiServer reverse proxy configuration
      POSTGRES_USER: ${JELLYSTAT_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${JELLYSTAT_DB_PASSWORD:-mypassword}
      POSTGRES_DB: ${JELLYSTAT_DB_NAME:-jellystat}
      TZ: ${TIMEZONE}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - ${VOLUMES_DIR}/jellystat-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${JELLYSTAT_DB_USER:-postgres} -d ${JELLYSTAT_DB_NAME:-jellystat}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      # Caddy reverse proxy configuration
      - "caddy=jellystat.${RASPISERVER_DOMAINS:-cckdev.es,localhost}"
      - "caddy.reverse_proxy={{upstreams 8080}}"
      - "caddy.header=/ X-Forwarded-Proto {scheme}"
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=database"
      - "raspiserver.description=PostgreSQL database for Jellystat analytics"

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    restart: unless-stopped
    environment:
      # RaspiServer reverse proxy configuration
      POSTGRES_USER: ${JELLYSTAT_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${JELLYSTAT_DB_PASSWORD:-mypassword}
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${JELLYSTAT_DB_NAME:-jellystat}
      JWT_SECRET: ${JELLYSTAT_JWT_SECRET:-my-secret-jwt-key}
      TZ: ${TIMEZONE}
      JELLYFIN_SERVER_URL: ${JELLYFIN_SERVER_URL:-http://jellyfin:8096}
      JELLYFIN_API_KEY: ${JELLYFIN_API_KEY:-}
    volumes:
      - ${VOLUMES_DIR}/jellystat-backup:/app/backend/backup-data
    ports:
      - ${JELLYSTAT_PORT:-3002}:3000
    depends_on:
      - jellystat-db
      - jellyfin
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      # Caddy reverse proxy configuration
      - "caddy=jellystat.${RASPISERVER_DOMAINS:-cckdev.es,localhost}"
      - "caddy.reverse_proxy={{upstreams 8080}}"
      - "caddy.header=/ X-Forwarded-Proto {scheme}"
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=media-analytics"
      - "raspiserver.description=Jellyfin usage statistics and analytics dashboard"