services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_DIR}/lidarr-config:/config
      - ${MEDIA_DIR}:/BibliotecaMultimedia
    ports:
      - ${LIDARR_PORT:-8686}:8686
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
