services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK=${UMASK:-022}
    volumes:
      - ${VOLUMES_DIR}/lidarr-config:/config
      - ${MEDIA_DIR}:/media # Music library access
      - ${DOWNLOADS_DIR:-./downloads}:/downloads # Download directory
    ports:
      - ${LIDARR_PORT:-8686}:8686
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8686/api/v1/system/status?apikey=$$(cat /config/config.xml | grep -oP '(?<=<ApiKey>)[^<]+')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - qbittorrent
      - prowlarr
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=music-management"
      - "raspiserver.description=Music collection manager and downloader"
