services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    restart: unless-stopped
    environment:
      # RaspiServer reverse proxy configuration
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK=${UMASK:-022}
    volumes:
      - ${VOLUMES_DIR}/mylar3-config:/config
      - ${MEDIA_DIR}:/media # Comics library access
      - ${DOWNLOADS_DIR:-./downloads}:/downloads # Download directory
    ports:
      - ${MYLAR3_PORT:-8090}:8090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api?cmd=getVersion&apikey=$$(cat /config/config.ini | grep -oP '(?<=api_key = )[^\\n]+')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - qbittorrent
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      # Caddy reverse proxy configuration
      - "caddy=mylar3.${RASPISERVER_DOMAINS:-cckdev.es,localhost}"
      - "caddy.reverse_proxy={{upstreams 8090}}"
      - "caddy.header=/ X-Forwarded-Proto {scheme}"
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=comics-management"
      - "raspiserver.description=Comic book collection manager and downloader"
