services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK=${UMASK:-022}
      - LANG_FLAGS_WAIT_SECONDS=${LANG_FLAGS_WAIT_SECONDS:-30}
    volumes:
      - ${VOLUMES_DIR}/radarr-config:/config
      - ${MEDIA_DIR}:/media
      - ${DOWNLOADS_DIR:-./downloads}:/downloads
      - ${VOLUMES_DIR}/radarr-custom-services.d:/custom-services.d
      - ../../arr-scripts/radarr:/custom-cont-init.d:ro
      - ./flags:/flags:ro
    ports:
      - ${RADARR_PORT:-7878}:7878
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/api/v3/system/status?apikey=$$(cat /config/config.xml | grep -oP '(?<=<ApiKey>)[^<]+')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - qbittorrent
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=media-management"
      - "raspiserver.description=Movie automation and management"
