services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}    
      - UMASK=${UMASK}
      - LANG_FLAGS_WAIT_SECONDS=${LANG_FLAGS_WAIT_SECONDS:-30}
    volumes:
      - ${VOLUMES_DIR}/sonarr-config:/config
      - ${MEDIA_DIR}:/BibliotecaMultimedia
      - ${VOLUMES_DIR}/sonarr-custom-services.d:/custom-services.d
      - ../../apps/mediaserver/sonarr-arr-scripts:/custom-cont-init.d:rw
      - ../../flags:/flags:rw
      - ${VOLUMES_DIR}/jellyfin-config/:/jellyfin-config:rw
    ports:
      - ${SONARR_PORT:-8989}:8989
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
