services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - DOCKER_MODS=${DOCKER_MODS:-ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest}
    volumes:
      - ${VOLUMES_DIR}/qbittorrent-config:/config:rw
      - ${DOWNLOADS_DIR:-./downloads}:/downloads:rw
      - ${MEDIA_DIR}:/media:ro
    ports:
      - ${QBITTORRENT_PORT:-8080}:8080
      - ${QB_TORRENTING_PORT:-6881}:6881
      - ${QB_TORRENTING_PORT:-6881}:6881/udp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "raspiserver.category=downloads"
      - "raspiserver.description=BitTorrent client with web interface"
